### ISSUE TITLE
Use of the @extend function inside the @media quries

### ISSUE THREAD

**Issue by gautam071** [sass/sass#3368] opened 2022-07-29 10:16 UTC
When I tried to use @extend inside the @media query, it threw an error. I am still unable to find a solution to this issue. It would be helpful if you share any suggestions for this.

## Code 
```
.product-image {
    @extend .w-80;
    @extend .h-80;
}

@media screen and (min-width: 1200px) {
    .product-image {
        @extend .w-193;
        @extend .h-193;
    }
}
```

## Error
```
Error: You may not @extend an outer selector from within @media.
       You may only @extend selectors within the same directive.
       From "@extend .w-193" on line 21 of assets/css/bundled-product.scss.
        on line 155 of assets/css/_utilities.scss
```

**Comment by nex3** [comment] 2022-08-02 20:30
Duplicate of #1050

**Closed as not planned by nex3** 2022-08-02 20:30 UTC
