### ISSUE TITLE
sass ampersand(&) of html element within class

### ISSUE THREAD

**Issue by yonatanmn** [sass/sass#1695] opened 2015-04-14 10:09 UTC
This is fairly simple :

```
h2{
    color:blue;
    &.someClass{
         color: red;
      }
   } 
//output:
   h2{color:blue;}, h2.someClass{color: red;}
```

but when I try the other way around it's not working:

```
 .someClass{
        color: red;
        h2&{
            color:blue;
        }
    }
//error: invalid selector after h2

//what I want to get: 
  h2.someClass{color:blue;}, .someClass{color: red;}
```

Is this a bug? I presumed that the compiler will take the parent string as it is `.someClass` and replace `h2&` with that, resulting in : `h2.someClass` 

Obviously, those won't work: 

`&h2`  ->`.someClassh2`,

`& h2` ->`.someClass h2`,

`h2 &` ->  `h2 .someClass`

Any solutions? (first asked at [stackoverflow](http://stackoverflow.com/questions/29623636/sass-ampersand-of-html-element-within-class), but I think it belongs here)

**Comment by cimmanon** [comment] 2015-04-14 14:47
Duplicate of https://github.com/sass/sass/issues/1369

**Closed as completed** 2015-04-21 03:38 UTC
