### ISSUE TITLE
Parser should throw error if invalid whitespace appears in input sass file

### ISSUE THREAD

**Issue by telekid** [sass/sass#1984] opened 2016-02-04 21:52 UTC
If a non-standard whitespace character is included in a SASS file, SASS will silently include that whitespace in the emitted file. This can become a debugging nightmare.

Example:
http://codepen.io/anon/pen/jWvJRe?editors=1100

**Comment by chriseppstein** [comment] 2016-02-08 18:47
Duplicate of #1976.

**Closed as completed by chriseppstein** 2016-02-08 18:47 UTC
