### ISSUE TITLE
Add a symbol to get only the parent selector

### ISSUE THREAD

**Issue by qmhc** [sass/sass#3638] opened 2023-07-19 02:42 UTC
## Description

When we use nested selectors, there is a situation as follows (when using components in framework):

```html
<!-- user code -->
<div class="a">
  <!-- .b is an encapsulated component -->
  <div class="b">
    <div class="b-c">
      <div class="b-d"></div>
    </div>
    <div class="b-e"></div>
  </div>
  <!-- -->
</div>
```

```scss
.a {
  .b {
    // ...

    // We expect to get selector `.a .b-c .b-d`, but actually it will be `.a .b-c .a .b-d`
    &-c &-d {
      // ...
    }

    // So we always need to specify the full selector of .b-d element
    &-c .b-d {
      // ...
    }
  }
}
```

[Playground](https://sass-lang.com/playground/#MTEuYSUyMCU3QiUwQSUyMCUyMC5iJTIwJTdCJTBBJTIwJTIwJTIwJTIwJTI2LWMlMjAlMjYtZCUyMCU3QiUwQSUyMCUyMCUyMCUyMCUyMCUyMGNvbG9yJTNBJTIwcmVkJTNCJTBBJTIwJTIwJTIwJTIwJTdEJTBBJTBBJTIwJTIwJTIwJTIwJTI2LWMlMjAuYi1kJTIwJTdCJTBBJTIwJTIwJTIwJTIwJTIwJTIwY29sb3IlM0ElMjBibHVyJTNCJTBBJTIwJTIwJTIwJTIwJTdEJTBBJTIwJTIwJTdEJTBBJTdEJTBB)

## Suggested solution

If there is a symbol (such as `^`) can only get the parent selector but not the full upstream selector, it would be very helpful.

```scss
.a {
  .b {
    // ...

    // `^` only get the parent selector
    &-c ^-d {
      // ...
    }

    // Maybe can get number of parent selectors via using it multiple times
    ^^-c {
      // equals to `.a .b-c`
      // ...
    }
  }
}
```

**Comment by nex3** [comment] 2023-07-19 21:14
Duplicate of https://github.com/sass/sass/issues/3637

**Closed as not planned by nex3** 2023-07-19 21:14 UTC
