### ISSUE TITLE
Allow step-size in @for block

### ISSUE THREAD

**Issue by thany** [sass/sass#1776] opened 2015-07-15 11:59 UTC
It would be nice to be able to declare a step-size when looping through a number with a `@for` block. I'm thinking maybe something like this:

```
@for $var from 10 through 90 step by 5 {
  //awesomess
}
```

Would be an easier / more readable / more declarative way to write:

```
$var: 10
@while $var <= 90 {
  //awesomess
  $var: $var + 5;
}
```

**Comment by cimmanon** [comment] 2015-07-15 12:08
Duplicate of https://github.com/sass/sass/issues/691

**Comment by nex3** [comment] 2015-07-17 22:20
Specifically see [this comment](https://github.com/sass/sass/issues/691#issuecomment-18172435).

**Closed as completed** 2015-07-17 22:19 UTC
