### ISSUE TITLE
Sass 3.4.13 fails to compile then keeps returning errors related to ‘listen’

### ISSUE THREAD

**Issue by Wordius** [sass/sass#1718] opened 2015-05-05 19:35 UTC
The ‘listen’ gem has been updated to the latest version. Here is the error returned – cut short because it just keeps going:

```
$ sass --watch sites/dev_sites/wordius/kirby/assets/sass:sites/dev_sites/wordius/kirby/assets/css
>>> Sass is watching for changes. Press Ctrl-C to stop.
        ** ERROR: directory is already being watched! **

        Directory: /Users/jeffporter/.Trash/SpiderOak Hive

        is already begin watched through: /Users/jeffporter/SpiderOak Hive

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /Users/jeffporter/Library/Mobile Documents

        is already begin watched through: /Users/jeffporter/Library/Mobile Documents

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /Users/jeffporter/Movies/iMovie Library 1.imovielibrary/.fcpcache

        is already begin watched through: /Users/jeffporter/Movies/iMovie Library 1.imovielibrary

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /Users/jeffporter/Movies/iMovie Library.imovielibrary/.fcpcache

        is already begin watched through: /Users/jeffporter/Movies/iMovie Library.imovielibrary

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
^C        ** ERROR: directory is already being watched! **

        Directory: /Users/jeffporter/.Trash/Hazel (1099).prefPane/Contents/Resources/English.lproj

        is already begin watched through: /Users/jeffporter/.Trash/Hazel (1099).prefPane/Contents/Resources/en.lproj

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /Users/jeffporter/.Trash/Hazel (1200).prefPane/Contents/Resources/English.lproj

        is already begin watched through: /Users/jeffporter/.Trash/Hazel (1200).prefPane/Contents/Resources/en.lproj

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /Users/jeffporter/.Trash/Hazel (1215).prefPane/Contents/Resources/English.lproj

        is already begin watched through: /Users/jeffporter/.Trash/Hazel (1215).prefPane/Contents/Resources/en.lproj

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /Users/jeffporter/.Trash/Hazel (1227).prefPane/Contents/Resources/English.lproj

        is already begin watched through: /Users/jeffporter/.Trash/Hazel (1227).prefPane/Contents/Resources/en.lproj

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
        ** ERROR: directory is already being watched! **

        Directory: /Users/jeffporter/.Trash/Hazel (1232).prefPane/Contents/Resources/English.lproj

        is already begin watched through: /Users/jeffporter/.Trash/Hazel (1232).prefPane/Contents/Resources/en.lproj

        MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
^C/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:90:in `run': Interrupt
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:90:in `block in signal'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:87:in `handle_interrupt'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/thread.rb:87:in `signal'
    from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/mailbox.rb:41:in `<<'
    from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/proxies/actor_proxy.rb:35:in `terminate!'
    from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:65:in `terminate!'
    from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:72:in `block (2 levels) in shutdown'
    from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:70:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:70:in `block in shutdown'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
    from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:66:in `shutdown'
    from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid.rb:156:in `shutdown'
    from /Library/Ruby/Gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid.rb:145:in `block in register_shutdown'
```

**Comment by Wordius** [comment] 2015-05-06 10:57
Note that if I `cd` to the ‘assets’ directory  and run

`sass --watch sass:css`

Sass compiles and, so far, the errors haven’t appeared.

**Comment by nex3** [comment] 2015-05-08 21:37
Duplicate of #1469.

@Wordius Check out the questions I asked @WillsB3 on that issue, and provide your own answers to them there.

**Closed as completed by nex3** 2015-05-08 21:37 UTC
