### ISSUE TITLE
Allow to save @content into a variable

### ISSUE THREAD

**Issue by wintercounter** [sass/sass#1668] opened 2015-03-13 09:55 UTC
It would be nice to allow to save @content to a variable.

Example situation:
1. Using mixins for different media query rules.
2. Instead of putting several times the same media query rule into the output i save the contents into a list.
3. I will render each corresponding content at the end of the compilation as a last step so there will be no duplication and the order of media queries can be controlled.

What do you think?

**Comment by lolmaus** [comment] 2015-03-13 10:25
Duplicate of #1582.

**Comment by wintercounter** [comment] 2015-03-13 10:46
Oh, sorry. Can be closed.

**Closed as completed** 2015-06-22 22:57 UTC
