### ISSUE TITLE
[Feature Request] introduce a config file like ".sassrc" or something else

### ISSUE THREAD

**Issue by KunalTanwar11** [sass/sass#3307] opened 2022-05-07 16:47 UTC
Sass could have a `config` file (which you save in the base dir) in which users can set options at once for compilation instead of using `javascript`.

### For Example
`.sassrc`
```js
module.exports = {
  sourceMaps: false,
  outputStyle: 'compressed' | 'expanded',
  // etc...
}
```

**Comment by nex3** [comment] 2022-05-10 20:27
Duplicate of https://github.com/sass/sass/issues/2669

**Closed as completed by nex3** 2022-05-10 20:27 UTC
