### ISSUE TITLE
on watch, is compiling css files too

### ISSUE THREAD

**Issue by jakeparis** [sass/sass#2763] opened 2019-10-25 20:49 UTC
I would like sass to watch a directory and compile the .scss files to .css files in the same directory. When I do `sass --watch css:css` or `sass --watch css/:css/` I get an infinite loop of sass attempting to compile a css file in that dir to itself. Like:
```
Compiled css/style.scss to css/style.css.
Compiled css/style.css to css/style.css.
Compiled css/style.css to css/style.css.
Compiled css/style.css to css/style.css.
Compiled css/style.css to css/style.css.
Compiled css/style.css to css/style.css.
```
until I quit the execution. 

Sass should either _not_ compile .css files, or there should be a flag indicating which extensions to watch, or something like `sass --watch css/*.scss:css/` should work.

**Comment by nex3** [comment] 2019-10-25 20:58
Duplicate of https://github.com/sass/dart-sass/issues/853

**Closed as completed by nex3** 2019-10-25 20:58 UTC
