### ISSUE TITLE
@include $var

### ISSUE THREAD

**Issue by MartinMuzatko** [sass/sass#2102] opened 2016-07-21 11:19 UTC
Hello there!

I'm trying to include mixins based on a list of features, to alllow on-demand features.

``` sass

$features: (
    'order'
    'offset'
    'layout'
    'flex'
    'layout-align'
    'visibility'
);

@each $feature in $features {
    /* "#{$feature}-for-name(#{$name})" */
    @include "#{$feature}"-for-name($name);
}
```

Any help is very much appreciated.
I think include isn't able to work with variables, since it demands a key, not a string.
Since I also can't evaluate a string, I'm not sure what I should do anymore.

Ideas?

```
{ [Error: Invalid CSS after "...       @include": expected identifier, was '"#{$feature}"-for-n']
  formatted: 'Error: Invalid CSS after "...       @include": expected identifier, was \'"#{$feature}"-for-n\'\n        on line 337 of src/flex-grid.scss\n>>     [layout-margin]  > [flex],\n   --------^\n',
  message: 'Invalid CSS after "...       @include": expected identifier, was \'"#{$feature}"-for-n\'',
  column: 9,
  line: 337,
  file: 'flex-grid.scss',
  status: 1 }

```

**Comment by chriseppstein** [comment] 2016-07-21 18:51
Duplicate of #739

**Closed as completed by chriseppstein** 2016-07-21 18:51 UTC
