### ISSUE TITLE
Space in media feature of @media query

### ISSUE THREAD

**Issue by dks17** [sass/sass#2212] opened 2016-12-14 12:01 UTC
media.css.scss file:
```
@media (min-width: 100px) and (max-width: 200px) {
  .box {
    background-color: green;
  }
}
```

Run:
sass -t compressed css/media.css.scss css/media.min.css

After compresed with sass media.min.css file:
`@media (min-width: 100px) and (max-width: 200px){.box{background-color:green}}`

But it could be without spaces between media feature's name and value:
`@media (min-width:100px) and (max-width:200px){.box{background-color:green}}`

Both compressed code also passed validation on https://jigsaw.w3.org/css-validator/

I noticed this distinction when tested site performance with https://gtmetrix.com and it offered 
> "Minify CSS for the following resources to reduce their size by 15B (1% reduction)."

As you might guess there were 15 media features with one space in each.

I know that this improvement offered before, but there was a bunch of improvements.
Improvements to the minifier #687

Removing spaces would be nice.

**Comment by nex3** [comment] 2016-12-14 20:35
Duplicate of #1296.

**Closed as completed by nex3** 2016-12-14 20:35 UTC
