### ISSUE TITLE
input&

### ISSUE THREAD

**Issue by daleyjem** [sass/sass#1694] opened 2015-04-12 05:54 UTC
In the practice of trying to keep code compartmentalized, not sure how this is still an issue with SASS (LESS can do it):

```
.form-component {
    input& {
        color: red;
    }

    textarea& {
        color: blue;
    }
}
```

**Comment by cimmanon** [comment] 2015-04-12 10:50
Duplicate of https://github.com/sass/sass/issues/1369

**Closed as completed** 2015-04-21 03:39 UTC
