### ISSUE TITLE
Bad negotiation during build and compressed output

### ISSUE THREAD

**Issue by Kcko** [sass/sass#1908] opened 2015-11-23 14:41 UTC
my code: 

```
$colors: 
(
    white   : #ffffff,
    mint    : #00a596,
    mintBlue: #00dcd5,
    orange  : #ff3228,
    yellow  : #ffbe00,
    purple  : #6e32c8,
    blue    : #0091ff,
    green   : #3cb446,
    black   : #000000,
    gray    : #999999,
);


@function color($key) {
  @if map-has-key($colors, $key) {
    @return map-get($colors, $key);
  }

  @warn "Unknown `#{$key}` in $colors.";
  @return null;
}

.aw-select-student-map + .aw-select
{
    @each $color in (yellow, green, orange, blue)
    {


        .body ul li[data-color="#{$color}"] {color: color($color)};

        .body ul li[data-color="#{$color}"].selected,
        .body ul li[data-color="#{$color}"]:hover
        {
            background: color($color);
            color: #fff;
        }
    }

}
```

When i set  output_style    = :compressed  in config.rb output is without yellow color the other colors are transferred.

When i set output_style = :expanded  yellow color is presented.

Its a bug or what im doing wrong?
Sass version is **Sass 3.4.18 (Selective Steve)**

**Comment by cimmanon** [comment] 2015-11-23 14:58
Duplicate of https://github.com/sass/sass/issues/1256

**Comment by chriseppstein** [comment] 2016-04-11 20:53
color names are color values and will be compressed when being output. Use quotes to avoid this.

**Closed as completed by chriseppstein** 2016-04-11 20:53 UTC
