### ISSUE TITLE
Uninitialized constant Sass::Deprecation

### ISSUE THREAD

**Issue by robinboening** [sass/sass#2344] opened 2017-07-12 18:02 UTC
I am using sass in a rails project where I am also using `sassc-rails`. However, after updating `sass` from `v3.4.23` to `v3.4.25` I get this error when booting the rails app:

```
/Users/robin/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.1/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'sassc-rails'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Sass::Deprecation
Backtrace for gem load error is:
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sass-3.4.25/lib/sass/script/value/string.rb:5:in `<class:String>'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sass-3.4.25/lib/sass/script/value/string.rb:4:in `<module:Value>'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sass-3.4.25/lib/sass/script/value/string.rb:2:in `<top (required)>'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sassc-1.11.2/lib/sassc/script.rb:32:in `require'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sassc-1.11.2/lib/sassc/script.rb:32:in `<top (required)>'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sassc-1.11.2/lib/sassc.rb:8:in `require_relative'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sassc-1.11.2/lib/sassc.rb:8:in `<top (required)>'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sassc-rails-1.3.0/lib/sassc/rails.rb:3:in `require'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sassc-rails-1.3.0/lib/sassc/rails.rb:3:in `<top (required)>'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sassc-rails-1.3.0/lib/sassc-rails.rb:7:in `require_relative'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/sassc-rails-1.3.0/lib/sassc-rails.rb:7:in `<top (required)>'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `each'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.1/lib/bundler/runtime.rb:77:in `block in require'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `each'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.1/lib/bundler/runtime.rb:66:in `require'
/Users/robin/.rvm/gems/ruby-2.3.1/gems/bundler-1.15.1/lib/bundler.rb:108:in `require'
/Users/robin/code/rails/hijabvibe/config/application.rb:16:in `<top (required)>'
```

In `lib/sass/script/value/string.rb:5` `Sass::Deprecation` is used but for some reason its not available. If I manually `require "sass/deprecation"` in that file, it works.

In `engine.rb:4` `sass/deprecation` gets required. I bit further down on line 47 in `engine.rb` `sass/script` gets required which requires `sass/script/value` which requires `sass/script/value/string`.

I haven't investigated much so I don't really know why its not available, but it seems a bit weird to me.

Just a few weeks ago this Deprecation class got introduced with this commit: 9c189635e5f0c0c7dbf54bf4147d54bee2a0d075

**Comment by nex3** [comment] 2017-07-12 23:11
Duplicate of #2338.

**Closed as completed by nex3** 2017-07-12 23:11 UTC

**Comment by meowsus** [comment] 2017-07-12 23:20
Related PR in sassc-ruby: https://github.com/sass/sassc-ruby/pull/68
