### ISSUE TITLE
Sass 3.4.17 bug with @import. Fonts not loaded in Ruby on Rails 4

### ISSUE THREAD

**Issue by Sega100500** [sass/sass#1810] opened 2015-08-25 12:44 UTC
Rollback to 3.4.16 solve problem

RoR 4.2.4: Custom fonts not loaded in production
https://github.com/rails/rails/issues/21367

**Comment by cimmanon** [comment] 2015-08-25 12:53
Duplicate of https://github.com/sass/sass/issues/1808

**Comment by Sega100500** [comment] 2015-08-25 16:53
RoR 4.2.4: Custom fonts not loaded in production:

Closing since **it is a sass bug**.

**Comment by Sega100500** [comment] 2015-08-25 16:57
**Important!**
When I run 'rake assets:precompile' all work fine! 
But, In config/environments/production.rb I wrote:
**config.assets.compile = true**

@import "filename.css";
not working to access filename.css in production

https://github.com/rails/rails/issues/21367#issuecomment-134556939

**Comment by chriseppstein** [comment] 2015-08-25 20:12
Duplicate of #1806. Fixed in 3.4.18 which was just released.

**Closed as completed by chriseppstein** 2015-08-25 20:12 UTC
