### ISSUE TITLE
Radial gradient position being doubled on compile

### ISSUE THREAD

**Issue by ryanantonydunn** [sass/sass#1758] opened 2015-06-26 09:13 UTC
Just a little doubling bug when the radial gradient syntax is compiled.

``` css
.test {
  background: radial-gradient(at top right, #fff, #000);
}
```

Compiles to:

``` css
.test {
  background: radial-gradient(at top right at top right, #ffffff, #000000);
}
```

**Comment by cimmanon** [comment] 2015-06-26 10:49
Duplicate of https://github.com/Compass/compass/issues/1937

**Closed as completed** 2015-06-26 10:51 UTC
