### ISSUE TITLE
Improper substitution of `black` with `outputStyle: compressed`

### ISSUE THREAD

**Issue by chris-lock** [sass/sass#1922] opened 2015-12-03 19:56 UTC
``` SASS
@mixin test($name) {
  .selector-#{$name} {
    display: none;
  }
}

div {
  @include test(black);
}
```

expanded

``` SASS
div .selector-black {
  display: none;
}
```

compact

``` SASS
div .selector-black { display: none; }
```

compressed

``` SASS
.selector-#000{display:none}
```

**Comment by cimmanon** [comment] 2015-12-03 21:35
Duplicate of https://github.com/sass/sass/issues/1256

**Comment by davidkpiano** [comment] 2015-12-03 21:47
@chris-lock To fix, use `@include test('black')`, where `'black'` is a quoted string instead of a color value.

**Closed as completed** 2015-12-11 00:43 UTC
