### ISSUE TITLE
Assigning same value to multiple properties.

### ISSUE THREAD

**Issue by GMchris** [sass/sass#2129] opened 2016-08-30 14:35 UTC
Without using variables that is. I think something like the switch case fall through, could reduce the amount of code written. Here's a couple of syntax options I could see working.

```
.element {
  height, max-height, min-height: 100px;
}
```

This is the one I would prefer, as it doesn't look like you just forgot to enter a value, and would probably look even neater with a newline after each comma.

```
.element {
  height:
  max-height:
  min-height: 100px;
}
```

I feel like it's a good thing to have if you ever need it. Just a small and simple cheat to write less.

**Comment by jessepinuelas** [comment] 2016-08-30 16:00
@GMchris, Sounds like a mixin would be a better solution, in my opinion. 

**Some potential issues** 
- automatically arranging css properties by alphabetical order

**Comment by GMchris** [comment] 2016-08-31 08:01
@jessepinuelas How do you mean? Wouldn't properties be evaluated first, and all assigned 100px (in this case), after which additional manipulations could be applied. And by mixin I assume you mean something like:

`@include multiple((max-height, min-height, height), 100px)`

But this kind of defeats the purpose of writing less, and on top of that is less readable.

**Comment by chriseppstein** [comment] 2016-08-31 20:34
Duplicate of #109

**Closed as completed by chriseppstein** 2016-08-31 20:34 UTC
