### ISSUE TITLE
Scenario where variable interpolation is more beneficial than using a map

### ISSUE THREAD

**Issue by mangelozzi** [sass/sass#2920] opened 2020-10-07 18:54 UTC
Firstly I have read many posts about this topic, and the counter is use maps, they are better suited. I agree. But I find myself in a situation, and [even Github.com style guide has the same problem](https://github.com/primer/css/blob/cdaaba69b53d6e57afd46b4b4b090bad4f8233f4/src/support/variables/color-system.scss#L8)  ... consumed with [this manual solution](https://github.com/primer/css/blob/cdaaba69b53d6e57afd46b4b4b090bad4f8233f4/src/utilities/colors.scss#L6).

If one has a long list of colour definitions, to create utility classes, one has to create a dictionary, then a function consuming the dictionary. This is much more code than just writing it all out by hand manually.

e.g. Colour definitions:
```sass
// FOR BLACK
   Colors with enough contrast to pass Webaim Accessibility
   Colors to work with black (black text on color, or color on black text)
$red_4black:            palette.$red_400
$pink_4black:           palette.$pink_300
$purple_4black:         palette.$purple_300
$deep_purple_4black:    palette.$deep_purple_300
$indigo_4black:         palette.$indigo_300
$blue_4black:           palette.$blue_500
$light_blue_4black:     palette.$light_blue_400
$cyan_4black:           palette.$cyan_400
$teal_4black:           palette.$teal_400
$green_4black:          palette.$green_500
$light_green_4black:    palette.$light_green_500
$lime_4black:           palette.$lime_500
$yellow_4black:         palette.$yellow_500
$amber_4black:          palette.$amber_500
$orange_4black:         palette.$orange_500
$deep_orange_4black:    palette.$deep_orange_400
$brown_4black:          palette.$brown_400
$gray_4black:           palette.$gray_500
$blue_gray_4black:      palette.$blue_gray_400

(and so on...)
```

First manually writing out classes:
```sass
    .red_4black
        color: support.$red_4black !important
    .pink_4black
        color: support.$pink_4black !important
    .purple_4black
        color: support.$purple_4black !important
    .deep_purple_4black
        color: support.$deep_purple_4black !important
    .indigo_4black
        color: support.$indigo_4black !important
    .blue_4black
        color: support.$blue_4black !important
    .light_blue_4black
        color: support.$light_blue_4black !important
    .cyan_4black
        color: support.$cyan_4black !important
    .teal_4black
        color: support.$teal_4black !important
    .green_4black
        color: support.$green_4black !important
    .light_green_4black
        color: support.$light_green_4black !important
    .lime_4black
        color: support.$lime_4black !important
    .yellow_4black
        color: support.$yellow_4black !important
    .amber_4black
        color: support.$amber_4black !important
    .orange_4black
        color: support.$orange_4black !important
    .deep_orange_4black
        color: support.$deep_orange_4black !important
    .brown_4black
        color: support.$brown_4black !important
    .gray_4black
        color: support.$gray_4black !important
    .blue_gray_4black
        color: support.$blue_gray_4black !important
```

With variable interpolation:
```sass
// Colors
$hues: ('red', 'pink', 'purple', 'deep_purple', 'indigo', 'blue', 'light_blue', 'cyan', 'teal', 'green', 'light_green', 'lime', 'yellow', 'amber', 'orange', 'deep_orange', 'brown', 'gray', 'blue_gray')

// COLORS ON BLACK
   Example of generated output for `red`
        .red_4black
            color: support.$red_4black !important
@each $hue in $hues
    .#{$hue}_4black
        color: #{$hue}_4black !important

@each $hue in $hues
    .#{$hue}_4white
        color: #{$hue}_4white !important

@each $hue in $hues
    .#{$hue}_muted
        color: #{$hue}_muted !important

@each $hue in $hues
    .#{$hue}_acsent
        color: #{$hue}_acsent !important
```

In the above scenario 4 huge dictionaries would have to be created, with no purpose other than to be consumed. I think in this situation it makes more sense to write it out by hand. So does github.com as shown above.

So although this issue will just be closed, I would just like to point out there are useful case's for variable interpolation. Yes its like fire, it can be bad, but that doesn't mean no-one in the world is allowed to use fire. Python has the ethios: "A language for consenting adults.". Such a philosphy empowers people (yes you can mess it up then, but you can also write very elegantly).

**Comment by Awjin** [comment] 2020-10-07 19:18
Duplicate of https://github.com/sass/sass/issues/132. Though this may have a niche use case, we've decided this feature would cause significantly more harm than good and prioritized that rationale.

**Closed as completed by Awjin** 2020-10-07 19:18 UTC

**Comment by mangelozzi** [comment] 2020-10-08 07:47
Point taken. I would just like to note that it's not really a niche usecase, every stylesheet system which has a color system, i.e. almost all, would benefit from it (e.g. the Github.com page you are currently viewing as explained above).
Cheers.

**Comment by mirisuzanne** [comment] 2020-10-18 19:53
@mangelozzi I've been playing with the built-in [`meta.module-variables()`](https://sass-lang.com/documentation/modules/meta#module-variables) function for generating maps from tokens. Something like this:

```scss
// tokens/_4black.scss (repeat for white, muted, etc)
$red_4black:            palette.$red_400
$pink_4black:           palette.$pink_300
$purple_4black:         palette.$purple_300
$deep_purple_4black:    palette.$deep_purple_300
// etc…
```

```scss
// tokens/_index.scss
@forward 'tokens/4black';
@forward 'tokens/4white';
@forward 'tokens/muted';
@forward 'tokens/accent';
```

```scss
// _utilities.scss
@use 'sass:meta';
@use 'tokens';
$tokens: meta.module-variables('tokens');

@each $name, $value in $tokens {
    .#{$name} {
        color: $value !important;
    }
}
```

Let the module system build your one-off maps for you. :)
