### ISSUE TITLE
Feature: factorise the same values

### ISSUE THREAD

**Issue by mr21** [sass/sass#2000] opened 2016-02-25 20:14 UTC
Hi :)

I didn't find an issue about this, but why can't we do something like this:

``` scss
.element {
    position: absolute;
    width:
    height: 100%;
    top:
    left: 0;
}
// inline
.element {
    position: absolute;
    width: height: 100%;
    top: left: 0;
}
```

Or maybe something like:

``` scss
.element {
    position: absolute;
    top, right, bottom, left: 10px;
}
```

**Comment by cimmanon** [comment] 2016-02-25 20:15
Duplicate of https://github.com/sass/sass/issues/109

**Comment by mr21** [comment] 2016-02-25 20:17
Oh my bad, I didn't search enough...

**Closed as completed** 2016-02-26 17:57 UTC
