### ISSUE TITLE
[feature-request]: Respect package.json exports

### ISSUE THREAD

**Issue by calebdwilliams** [sass/sass#3303] opened 2022-05-01 17:22 UTC
I might have [originally put this in the wrong place](https://github.com/sass/dart-sass/issues/1683), so I'm trying here. I'm happy to close whichever issue is wrong.

In version 12, Node added support for [subpath exports](https://nodejs.org/api/packages.html#subpath-exports) which allows package authors to define package entry points that may not necessarily correspond to the directory structure of the published package.

I would like to propose that Sass be given the ability to respect a package's exports. This would allow developers to publish several partials locally to break up logic or behavior while also controlling which files can be directly accessed by consumers. It would also allow package authors to provide clean entry points to their Sass files even if some circumstance necessitates the directory structure be more complex.

Obviously I realize that this could be seen as a breaking change, so would be happy to have this fall under a flag (either permanently or temporarily) such as --module-resolution=node or something else.

**Comment by jathak** [comment] 2022-05-02 20:23
Duplicate of #2739.

**Closed as completed by jathak** 2022-05-02 20:23 UTC
