### ISSUE TITLE
Add --ascii-only flag to avoid emitting Unicode at all

### ISSUE THREAD

**Issue by mbohovic** [sass/sass#3317] opened 2022-05-17 12:59 UTC
Source SCSS:

#test:before { content: "\2713"; }

Compiled css:

#test:before { content: "✓"; }

The html entity '\2713' is replaced with the actual symbol '✓' in the complied css and then, it's shown like this "eâœ“" on browsers.

The correct output should be like the input.

**Comment by stof** [comment] 2022-05-18 09:05
Well, all browsers are able to parse CSS as UTF-8 (unless they don't respect the CSS spec, as the CSS spec mandates support for Unicode). So to me, this looks like an issue in the way you serve your CSS (btw, by default, Sass will put a `@charset "UTF-8"` or a BOM at the beginning of the stylesheet to tell the browser it is UTF-8)

**Comment by nex3** [comment] 2022-05-23 20:39
Duplicate of https://github.com/sass/dart-sass/issues/568.

**Closed by nex3** 2022-05-23 20:39 UTC
