### ISSUE TITLE
Request: @import-once

### ISSUE THREAD

**Issue by liril-net** [sass/sass#2370] opened 2017-09-06 07:38 UTC
I have reviewed #156 but it do not fit my need. 

1. I have a component named `foo` with `foo.scss`.
2. I have a component named `bar` which depends on `foo` component.

If i only need `bar`, it works well with only one `foo.scss`. However, if i need both `foo` and `bar` and it will import `foo.scss` twice.

Is there anyway that i can only import `foo.scss` once? It may not be a good way to write a 'common.scss' which belongs to component `foo`. cause that i could have many components like `foo` and `foo` is also a standalone component.

**Comment by nex3** [comment] 2017-09-29 22:22
Duplicate of #156.

**Closed as completed by nex3** 2017-09-29 22:22 UTC
