### ISSUE TITLE
BEM-style elements and @extend

### ISSUE THREAD

**Issue by TheEponymousBob** [sass/sass#1725] opened 2015-05-15 11:52 UTC
Not sure if this is intended behaviour, but seems odd. I want several concrete blocks that have most sub-elements in common, but with some variations, so am looking at @extends. Trying something like the following:

```
%top-level {
  background: white;
  &__sub-item {
    background: none;
  }
}

.concrete {
  @extends %top-level;
}
```

Expecting: 

```
.concrete {
  background: white;
}
.concrete__sub-item {
  background: none;
}
```

but geting only

```
.concrete {
  background: white;
}
```

If I replace the nested selector with (for example) `& .child`, I get what I'd expect - an HTML child selector correctly shared by the @extends. Also, if I turn `%top-level` into a concrete class, the concatenated class works for it, but not its extension. I.e.:

```
.top-level {
    background: white;
    &__sub-item {
        background: none;
    }
    & .child {
        background: blue;
    }
}
.concrete {
    @extend .top-level;
}
```

gives:

```
.top-level, .concrete {
  background: white;
}
.top-level__sub-item {
  background: none;
}
.top-level .child, .concrete .child {
  background: blue;
}
```

**Comment by cimmanon** [comment] 2015-05-15 12:17
Change it to a class and you'll see what's actually happening:

``` scss
.top-level {
  background: white;
  &__sub-item {
    background: none;
  }
}

.concrete {
  @extend .top-level;
}
```

Output:

``` css
.top-level, .concrete {
  background: white;
}
.top-level__sub-item {
  background: none;
}
```

The only thing that makes an extend only selector different from any other selector is that it is suppressed in the final output.

**Comment by TheEponymousBob** [comment] 2015-05-15 12:24
Thanks - I checked that, and like I said, it shows the concatenation does work for the class itself, but my issue remains - we don't get a `.concrete__sub-item` rule via `@extends`.

**Comment by cimmanon** [comment] 2015-05-15 12:29
You aren't supposed to.  Extend only selectors aren't a search & replace job.  You're generating a `%top-level__sub-item` selector, so unless you extend _that_, you aren't going to get what you expect.

If that's the behavior you want, then you need to use a mixin.

**Comment by nex3** [comment] 2015-05-15 22:28
Duplicate of #1424 (among others).

**Closed as completed by nex3** 2015-05-15 22:28 UTC
