### ISSUE TITLE
Warnings : directory is already being watched 

### ISSUE THREAD

**Issue by isoph** [sass/sass#1625] opened 2015-02-04 15:25 UTC
Hello,
I had installed sass a while ago (mac os mavericks) and it was working fine, but recently I had warnings it had fallen back to polling rather than watching.
I installed the latest version of sass (3.4.10), it didn’t go away. 
I searched and found this:
https://stackoverflow.com/questions/10952906/sass-listen-has-fallen-back-to-polling
I followed their suggestion to install listen then rb-inotify.
Now when I do sass --watch /Users/input:/Users/output, I get:

> > > Sass is watching for changes. Press Ctrl-C to stop.

Then messages pile in the terminal: 

```
    ** ERROR: directory is already being watched! **

    Directory: /Users/username/Pictures/iPhoto Library/Originals

    is already begin watched through: /Users/username/Pictures/iPhoto Library/Masters

    MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
```

It doesn’t stop, going through various folders, until I stop sass…
Any idea how to fix that?

**Comment by chriseppstein** [comment] 2015-02-04 18:12
Hmmm. I specifically wrote code to [deduplicate watched paths](https://github.com/sass/sass/blob/stable/lib/sass/plugin/compiler.rb#L411-L425). I wonder if it's not working correctly or if @nex3 changed something that causes this to be bypassed now.

**Comment by isoph** [comment] 2015-02-04 22:24
What’s also weird is the directories being watched. Nowhere have I specified my iPhoto Library being watched for CSS change…

**Comment by nex3** [comment] 2015-02-07 02:04
Do you have any symlinks or other references from the directory in which you're running Sass to the directories that listen is complaining about? In what directory are you running Sass? What's the directory structure of your project? Of `/Users/input` and `/Users/output`?

This is a duplicate of #1469, though; let's continue the discussion there.

**Closed as completed by nex3** 2015-02-07 02:04 UTC
