### ISSUE TITLE
uninitialized constant Sass::Deprecation

### ISSUE THREAD

**Issue by HenokT** [sass/sass#2343] opened 2017-07-12 17:56 UTC
I get the following error when loading my application and it looks like its due to the sass tag version 3.4.25 that's brought in transitively by sassc-rails. When I force an earlier version in my Gemfile,  the error goes away. 

```
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'sassc-rails'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Sass::Deprecation
Backtrace for gem load error is:
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:5:in `<class:String>'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:4:in `<module:Value>'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:2:in `<top (required)>'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sassc-1.11.2/lib/sassc/script.rb:32:in `require'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sassc-1.11.2/lib/sassc/script.rb:32:in `<top (required)>'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sassc-1.11.2/lib/sassc.rb:8:in `require_relative'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sassc-1.11.2/lib/sassc.rb:8:in `<top (required)>'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sassc-rails-1.3.0/lib/sassc/rails.rb:3:in `require'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sassc-rails-1.3.0/lib/sassc/rails.rb:3:in `<top (required)>'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sassc-rails-1.3.0/lib/sassc-rails.rb:7:in `require_relative'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/sassc-rails-1.3.0/lib/sassc-rails.rb:7:in `<top (required)>'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/Users/dev/myapp/config/application.rb:7:in `<top (required)>'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command/actions.rb:15:in `require'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/console/console_command.rb:84:in `perform'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
/Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
	from /Users/dev/myapp/config/application.rb:7:in `<top (required)>'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command/actions.rb:15:in `require'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/console/console_command.rb:84:in `perform'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command/base.rb:63:in `perform'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command.rb:44:in `invoke'
	from /Users/dev/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>
```

**Comment by robinboening** [comment] 2017-07-12 18:09
haha, double posting: https://github.com/sass/sass/issues/2344 (5min later)

**Comment by nex3** [comment] 2017-07-12 23:11
Duplicate of #2338.

**Closed as completed by nex3** 2017-07-12 23:11 UTC

**Comment by meowsus** [comment] 2017-07-12 23:20
Related PR in sassc-ruby: https://github.com/sass/sassc-ruby/pull/68
