### ISSUE TITLE
[enhancement] using @extend in @media

### ISSUE THREAD

**Issue by jossef** [sass/sass#1951] opened 2016-01-05 09:56 UTC
The following scss won't compile,

```
html, body {
  padding: 0;
  margin: 0;
}

.a4 {
  width: 210mm;
  min-height: 297mm;
}

@page {
  size: A4;
  margin: 0;
}

@media screen {
  html, body {
    @extend .a4
  }

}
```

```
error ... (You may not @extend an outer selector from within @media. You may only @extend selectors within the same directive.
```

![image](https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif)
## As a DX (developer experience) suggestion

please support that

**Comment by cimmanon** [comment] 2016-01-05 13:09
Duplicate of https://github.com/sass/sass/issues/1050

**Closed as completed** 2016-01-05 17:42 UTC
