### ISSUE TITLE
Sass 1.8 在vite中全局引入mixin方法，使用时依然报 Undefined mixin.

### ISSUE THREAD

**Issue by zhangshuanglibaby** [sass/sass#3972] opened 2024-11-01 14:22 UTC
环境：vue3.5 + vite5.4 + sass1.8
1. 已经在asstes/styles中定义了minxins文件
2. 在vite.config.ts中想实现全局自动引入
3. 但是在使用的时候 依旧会报错
<img width="337" alt="image" src="https://github.com/user-attachments/assets/6db1a9b2-e054-470d-89eb-aaa95f732ccd">
<img width="603" alt="image" src="https://github.com/user-attachments/assets/474d7ac2-2467-4b9a-97a1-8b64218a5a87">
<img width="504" alt="image" src="https://github.com/user-attachments/assets/5cdb40af-740f-4ed5-815d-06067b7e18bd">

**Comment by nex3** [comment] 2024-11-01 22:44
1. I'm assuming you mean Dart Sass 1.**80**.0, not 1.**8**.0, which was released in June 2018.
2. `addtionalData` is not a Sass feature. I believe it either comes from Vite or from the WebPack plugin, so I can't really help you debug it because I don't know how it works.
3. Generally speaking, we recommend you avoid using it and instead explicitly add `@use` rules to each file that needs them. Part of the point of `@use` is to make it locally clear where each name in a file comes from and adding global loads defeats that purpose.

**Closed as not planned by nex3** 2024-11-01 22:44 UTC

**Comment by CassandraCat** [comment] 2024-11-22 13:07
same issues.
As soon as I use @use, I get an error about undefined mixin.

**Comment by nex3** [comment] 2024-11-22 23:05
@CassandraCat Please file a separate issue with a stand-alone reproduction.
