### ISSUE TITLE
node版本升级到21.x后，打包报错

### ISSUE THREAD

**Issue by jishuweb** [sass/sass#3722] opened 2023-10-18 08:02 UTC
原始报错片段：error during build:
TypeError: Cannot read properties of undefined (reading 'indexOf')
    at D:\study\web_admin\music\node_modules\.pnpm\sass@1.69.4\node_modules\sass\sass.dart.js:116832:12
报错原因：
sass判断的源码片段：var isBrowser = typeof navigator == "object";
sass中用navigator来判定是否是浏览器环境，在node20以前是正常的，node在21.x后新增了navigator对象，这个判断就不对了

**Comment by gabrielrbarbosa** [comment] 2023-10-18 16:44
Related:
https://stackoverflow.com/questions/77314799/vitecss-preprocessor-dependency-sass-failed-to-load-cannot-read-propertie
https://stackoverflow.com/questions/77313962/vite-project-starts-with-an-error-preprocessor-dependency-sass-failed-to-load
https://stackoverflow.com/questions/77315051/preprocessor-dependency-sass-failed-to-load

Using node 21.x

**Comment by nex3** [comment] 2023-10-18 21:51
Duplicate of https://github.com/dart-lang/sdk/issues/53784.

**Closed as completed by nex3** 2023-10-18 21:51 UTC
