### ISSUE TITLE
Color white has no channel named hue

### ISSUE THREAD

**Issue by jgthms** [sass/sass#3938] opened 2024-09-18 14:45 UTC
Hi,

I'm trying to migrate from using `hue($color)` to using `color.channel($color, "hue")`.

Before:

```scss
@use "sass:color";
$hue: hue(white);
@debug $hue;
```

Now:
```scss
@use "sass:color";
$hue: color.channel(white, "hue");
@debug $hue;
```

I get this error:
```
@error:2
$channel: Color white has no channel named hue.
  ╷
2 │ $hue: color.channel(white, "hue");
  │       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  - 2:7  root stylesheet
```

Does `$color` need to be in hsl format for this to work? This would defeat the purpose of the function. Or am I missing something?

**Comment by nex3** [comment] 2024-09-19 01:16
Duplicate of https://github.com/sass/dart-sass/issues/2353

**Closed as not planned by nex3** 2024-09-19 01:16 UTC
