### ISSUE TITLE
Syntax to DRY up dimensions

### ISSUE THREAD

**Issue by creativetags** [sass/sass#2281] opened 2017-05-03 15:26 UTC
Would it work to have a syntax like this:

    .my-class
      margin:
        right, left: 15px
        top, bottom: 10px

and

    .my-other-class
      margin:
        right, bottom: 15px
        top, left: 10px

kinda like shorthand syntax in css `margin: 10px 15px` but where you could choose which sides were matched and you didn't have to override all existing sides. That last point is the biggest use case - where you just want to set margin-left and margin-right to some same value without overriding top and bottom.

**Comment by nex3** [comment] 2017-05-18 21:56
Duplicate of #109.

**Closed as completed by nex3** 2017-05-18 21:56 UTC
