### ISSUE TITLE
Map variables formatting error

### ISSUE THREAD

**Issue by josh-hernd** [sass/sass#3388] opened 2022-09-02 20:05 UTC
This is the initial way i ran into the problem, i was reading [dev.io ](https://dev.to/khayden73/creating-a-css-color-palette-from-sass-variables-14fo) article on how to create Color Palettes. 

Mapped variables do not work with style.sass when formatted, although it works fine without formatting(single line variable).
I am well aware that mapped variables work in style.scss but it would be ideal keeping the project concise and not have .sass and .scss mixed in. 

Here is a [Codepen](https://codepen.io/josue-hernandez-the-vuer/pen/XWqWZpB) to demonstrate the error.
<img width="426" alt="palette" src="https://user-images.githubusercontent.com/73445894/188228050-b84f7cf8-e16f-4448-a989-f0355c7520a6.png">

**Comment by jathak** [comment] 2022-09-06 20:26
Duplicate of #216.

In the meantime, you can use the SCSS syntax if you want to have expressions span multiple lines.

**Closed as completed by jathak** 2022-09-06 20:26 UTC
