### ISSUE TITLE
support @use and @forward  configuring with path

### ISSUE THREAD

**Issue by victor-assis** [sass/sass#2859] opened 2020-05-11 13:19 UTC
Exemple:
```
// _library-1.scss
$black: #000000 !default;
$white: #ffffff !default;

// _library-2.scss
$black: #242323 !default;

// index.scss
@forward 'library-1' with (
  'library-2'
);
```

**Comment by Awjin** [comment] 2020-05-13 21:19
Duplicate of #2846—in particular https://github.com/sass/sass/issues/2846#issuecomment-618042396.

**Closed as completed by Awjin** 2020-05-13 21:19 UTC

**Comment by Awjin** [comment] 2020-05-13 21:29
In general, `@use ... with` isn't meant to handle advanced use cases. I'd recommend taking a look at https://sass-lang.com/documentation/at-rules/use#with-mixins for alternatives.
