### ISSUE TITLE
looking for a feature： compile the SCSS into CSS with the help of '*' 

### ISSUE THREAD

**Issue by PLQin** [sass/sass#2866] opened 2020-06-04 07:13 UTC
Is there any way to do that ?
```
sass --watch **/:**/
```
or
```
sass --watch **/*.scss  **/*.css
```

**Comment by PLQin** [comment] 2020-06-04 07:22
@mirisuzanne @jathak @Awjin @nex3 please , help me

**Comment by jathak** [comment] 2020-06-18 20:43
Duplicate of sass/dart-sass#616.

**Closed as completed by jathak** 2020-06-18 20:43 UTC
