### ISSUE TITLE
How CSS4 color functions map to Sass color functions

### ISSUE THREAD

**Issue by kevinSuttle** [sass/sass#2174] opened 2016-10-19 16:04 UTC
Is there a correlation between them, and if not, are you planning on supporting them?

https://drafts.csswg.org/css-color/#modifying-colors
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#color_operations

**Comment by stevenvachon** [comment] 2016-10-27 17:11
Duplicate of #2078

**Closed as completed** 2016-10-27 18:01 UTC
