### ISSUE TITLE
Support @apply rule

### ISSUE THREAD

**Issue by yisibl** [sass/sass#1815] opened 2015-08-26 07:14 UTC
Specs: http://tabatkins.github.io/specs/css-apply-rule/
Support in polymer 1.0: https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins

``` css
:root {
  --toolbar-theme: {
    background-color: hsl(120, 70%, 95%);
    border-radius: 4px;
    border: 1px solid var(--theme-color late);
  };
  --toolbar-title-theme: {
    color: green;
  };
}

.toolbar {
  @apply --toolbar-theme;
}

.toolbar > .title {
  @apply --toolbar-title-theme;
}

.warning {
  --toolbar-title-theme: {
    color: red;
    font-weight: bold;
  };
}
```

**Comment by chriseppstein** [comment] 2015-08-27 20:49
Duplicate of #1128

**Closed as completed by chriseppstein** 2015-08-27 20:49 UTC
