### ISSUE TITLE
CSS Custom Properties and RGB

### ISSUE THREAD

**Issue by kylelavery88** [sass/sass#2311] opened 2017-06-10 23:28 UTC
The following is valid CSS but not valid SCSS...

```
:root {
	--opacity: 1;
	--color-rgb: 250, 167, 0;
	--color: rgb(var(--color-rgb));
}

p {
	--opacity: .2;
	background: rgba(var(--color-rgb), var(--opacity));
	color: var(--color);
}
```

err `wrong number of arguments (1 for 3) for 'rgb'`

**Comment by nex3** [comment] 2017-06-14 22:18
Duplicate of #2175.

**Closed as completed by nex3** 2017-06-14 22:18 UTC
