### ISSUE TITLE
Transparent one-argument mixins as custom properties

### ISSUE THREAD

**Issue by Marat-Tanalin** [sass/sass#1757] opened 2015-06-24 16:22 UTC
Hello. This is a feature request.

It would be nice to be able to define custom properties that would effectively work as one-argument mixins, for example:

```
@property size($value) {
    width:  $value;
    height: $value;
}
```

Usage:

```
.example {
    size: 20px;
}
```

Compiles to:

```
.example {
    width:  20px;
    height: 20px;
}
```

Compared with existing mixins, custom-properties have shorter, more elegant syntax which is easier to use and read inside sets of other properties. Compare property syntax:

```
.example {
    color: #ccc;
    size: 20px;
    z-index: 5;
}
```

and explicit-mixin syntax:

```
.example {
    color: #ccc;
    @include size(20px);
    z-index: 5;
}
```

Besides the `size` property shown in the examples above, the feature could be used for `margin-x` property (sets `margin-left` and `margin-right` to the same value at once), `margin-y` (like `margin-x`, but for vertical margins), `padding-x` (like `margin-x`, but for padding), `padding-y`, `border-radius-right` (rounds top right and bottom right corners at once), etc.

Thanks.

**Comment by cimmanon** [comment] 2015-06-24 16:27
Duplicate of https://github.com/sass/sass/issues/1573

**Comment by Marat-Tanalin** [comment] 2015-06-24 16:42
Thanks. FWIW, please note that my proposal has nothing to do with neither prefixing nor fallbacks for bleeding-edge features. It's just about brevity and ease to use and read stylesheet code by human.

As for possible collisions with future CSS-standard properties, we could just prefix custom properties like this:

```
.example {
    _size: 20px;
}
```

This would be anyway easier to use and read than explicit mixin-call syntax which is somewhat cumbersome and redundant in simple one-argument cases.

**Closed as completed** 2015-06-25 00:54 UTC

**Comment by Marat-Tanalin** [comment] 2015-06-25 21:20
What about omitting `@include` when calling a mixin not followed by a `{}` block?

```
.example {
    size(20px);
}
```

It does not contain a colon followed by a value, so it's certainly **not** a `property: value;` declaration.

And it is not followed by a `{}` block, so it's certainly **not** a nested rule. So there is no any ambiguity, as well as, unlike the originally-proposed transparent-property syntax, it cannot be confused with regular properties or conflict with future standard CSS properties in any way.

Thanks.

P. S. Please let me know if it'd be better to report a new issue related exactly to omitting `@include`.

**Comment by cimmanon** [comment] 2015-06-25 21:27
There is already an issue open for that (see: https://github.com/sass/sass/issues/366)

**Comment by Marat-Tanalin** [comment] 2015-06-25 21:50
#366 is almost entirely about **prefixes/postfixes** as an alternative to `@include`, while I propose to **omit** `@include` entirely.

I found just three comments related to omitting `@include`: [1](https://github.com/sass/sass/issues/366#issuecomment-21673261), [2](https://github.com/sass/sass/issues/366#issuecomment-21673443), [3](https://github.com/sass/sass/issues/366#issuecomment-11549365).

The first one states that "it has all the same language issues as the + did". But it's unclear what exact issues he means. As I said, there is no ambiguity: it's certainly not a declaration and not a nested rule.

The second one says that it looks "like a property with arguments more than a function". But there are no properties with arguments — neither in CSS nor in SCSS, so this does not look like a substantive argument.

The third comment has proposed to "add short syntax only for mixins without content block" which is in line with what I've proposed.

**Comment by Marat-Tanalin** [comment] 2015-07-03 22:38
So what about omitting `@include` given what I said in my previous [comment](https://github.com/sass/sass/issues/1757#issuecomment-115409145)? Thanks.
