### ISSUE TITLE
Code style with parent selector get's destroyed

### ISSUE THREAD

**Issue by alexhass** [sass/sass#1986] opened 2016-02-08 10:08 UTC
Based on "@mixin does-parent-exist" in sass documentation I created a mixin with this code to generate RTL css:

```
@mixin rtl {
  @if & {
    [dir="rtl"] & {
      @content;
    }
  }
  @else {
    [dir="rtl"] {
      @content;
    }
  }
}
```

The scss file looks like this:

```
ul,
ol,
dl {
  margin: 0 0 1em 1em;
  @include rtl() {
    margin: 0 1em 1em 0;
  }
}
```

and generated this broken RTL output:

```
ul,
ol,
dl {
  margin: 0 0 1em 1em;
}
[dir="rtl"] ul, [dir="rtl"]
ol, [dir="rtl"]
dl {
  margin: 0 1em 1em 0;
}
```

but should generate this output:

```
ul,
ol,
dl {
  margin: 0 0 1em 1em;
}
[dir="rtl"] ul,
[dir="rtl"] ol, 
[dir="rtl"] dl {
  margin: 0 1em 1em 0;
}
```

Is there a way to fix this? e.g. change the mixin code - or is this just a bug? I'm using compass.app that is based on jruby.

**Comment by chriseppstein** [comment] 2016-02-08 18:25
Duplicate of #1976.

**Closed as completed by chriseppstein** 2016-02-08 18:25 UTC
