### ISSUE TITLE
Bug extending a place‑holder

### ISSUE THREAD

**Issue by Hibou57** [sass/sass#1959] opened 2016-01-07 18:40 UTC
Using “Sass 3.2.12 (Media Mark)” on Ubuntu 14.04 32 Bits.

Given this:

```
%ph {
   &:hover {
      color: red;
   }
}

input {
   @extend %ph;
   color: green;
}

input {
   &[type] {
      @extend %ph;
      color: blue;
   }
}
```

Expected output should be this:

```
input:hover, input[type]:hover {
  color: red; }

input {
  color: green; }

input[type] {
  color: blue; }
```

It is this, instead:

```
input:hover {
  color: red; }

input {
  color: green; }

input[type] {
  color: blue; }
```

May be an Interesting track to note, is that if I comment‑out the `@extend %ph;` in the second statement, I got this:

```
input[type]:hover {
  color: red; }

input {
  color: green; }

input[type] {
  color: blue; }
```

The second statement seems to prevent the third statement to be handled as expected.

**Comment by chriseppstein** [comment] 2016-01-07 18:53
`input:hover` matches all the elements that `input[type]:hover` would match, so we don't output it as an optimization.

**Comment by Hibou57** [comment] 2016-01-07 19:18
Do you know both selectors do not weight the same?

This is not an optimisation, this is breaking CSS semantic.

**Comment by chriseppstein** [comment] 2016-01-07 19:37
@Hibou57 That's a fair point. @nex3 did all the extend optimizations so I'll let her respond.

**Comment by chriseppstein** [comment] 2016-01-07 19:40
@Hibou57 either way, Sass 3.2.12 is very old and I encourage you to upgrade -- any possible changes would only be made on the latest versions.

**Comment by davidkpiano** [comment] 2016-01-07 19:52
I think the issue is that @Hibou57 is treating the placeholder selector as a `@mixin`. Extended selectors should never have a specificity greater than the extending selector, which is why `:hover` is added to `input`, but not `input[type]`, since you can consider `%ph:hover` to have a specificity of `0 2 0`. The automatic insertion of `:hover` is necessary to abide by this rule, and is happenstance in this case (though it is peculiar how Sass decides to add that...)

A potential solution is to either use `@mixin` or to explicitly extend the `:hover` states:

``` scss
@mixin ph() {
  &:hover {
    // ... 
  }
}


// Or this...
%ph-hover {
  // ...
}

input:hover, input[type]:hover {
  @extend %ph-hover;
}
```

**Comment by Hibou57** [comment] 2016-01-08 02:54
I will look at `@mixin` later and will just comment on `@extend`.

> Extended selectors should never have a specificity greater than the extending selector

I solved the issue with a reorganisation based on this (I try to order rules from lower to greater specificity, in CSS, as much as possible). But as you've guessed, I was surprised by `@extend`'s behaviour, as unless I overlooked it, the documentation does not mention this specificity issue, and says this:

> @extend works by inserting the extending selector […] anywhere in the stylesheet that the extended selector […] appears.

May be this would be more intuitive if `@extend` was indeed just working like this.

Also, a bit before the documentation says:

> The @extend directive avoids these problems by telling Sass that one selector should inherit the styles of another selector.

And typically, in the computer language world, when a B inherits from an A, this means B is more specific than A (not entirely applicable here, that's just for the big picture).

May be optimisation should be left to another tool, in the UNIX way of “do one thing only, and do it well”. Or may be an option to disable this optimisation (which is not to me, sorry). If it's in the doc, I may have missed it, as I'm new to Sass. I will search the options list later …

P.S. There is someone at GitHub, named @extend, who will wonder why xe is mentioned so often here :-D .

**Comment by chriseppstein** [comment] 2016-01-08 17:41
PROTIP: If you backtick `@extend` it doesn't create a mention.

**Comment by nex3** [comment] 2016-01-08 22:22
There are very specific rules for which selectors may and may not be optimized out when resolving `@extend`s, which I [describe in detail here](https://github.com/sass/sass/issues/324#issuecomment-4607184). The second law says that the specificity of the generated selector must be greater than or equal to _the extending selector_ (in this case `input[type]`). This is satisfied by Sass's output: `input[type]` has specificity 11, and so does `input:hover`.

**Closed as completed by nex3** 2016-01-08 22:22 UTC

**Comment by Hibou57** [comment] 2016-01-09 01:19
@nex3, if this is per design (although unintuitive to me), these details should be in the documentation.

@chriseppstein 

> Sass 3.2.12 is very old 

That's what's in the Ubuntu 14.04 official repository, and there is no maintained PPA for Sass (the only one I could find is inactive since 2011).

**Comment by nex3** [comment] 2016-01-09 01:27
> if this is per design (although unintuitive to me), this details should be in the documentation.

Unfortunately, there's not a great place to put in-depth details like this in the current documentation structure. At some point I would like to produce a full specification, which would have room for this level of detail, but that's a very large undertaking.

**Comment by Hibou57** [comment] 2016-01-09 01:37
I hope I don't annoys too much with two comments I would like to add.

If this is in‑depth details which hardly get a place in the documentation, these details should be transparent (safely ignored), but they are not. So may be that's just too much for a specification.

The other point is that an optimization is supposed to preserve semantic. This one does not, as it actually change the meaning of the generated CSS (that's how I caught it, wondering what suddenly went wrong while rewriting a big CSS in Sass). So it should not be qualified as an optimization, rather as an Sass specific semantic.

I have to read the message you pointed to now :-p .

**Comment by nex3** [comment] 2016-01-09 02:53
> If this is in‑depth details which hardly get a place in the documentation, these details should be transparent (safely ignored), but they are not. So may be that's just too much for a specification.

High-level documentation like the reference can't possibly cover all user-visible behavior and still be usable by ordinary people trying to learn about the language. Detailed documentation about exactly how processes like `@extend` selector trimming work and which specific guarantees they make are the job of the spec.

> The other point is that an optimization is supposed to preserve semantic. This one does not, as it actually change the meaning of the generated CSS (that's how I caught it, wondering what suddenly went wrong while rewriting a big CSS in Sass). So it should not be qualified as an optimization, rather as an Sass specific semantic.

The specific name doesn't really matter. The point is that `@extend` is a Sass construct, and as such it's up to Sass to define exactly what it means. Our definition only guarantees a certain degree of specificity, and so given that guarantee we consider ourselves free to optimize away some intermediate selectors that aren't required to meet it.

**Comment by Hibou57** [comment] 2016-01-09 05:07
Now I know, so that's not for me I'm adding last words on this (closed for me too after that).

As a summary, the documentation says the software do one thing, while the software do another thing. In such cases, either the documentation needs to be fixed or the software needs to be fixed. You decided to do none. You are free to do so as Sass is yours not mine (*), and not solve the issue if you wish so. But please, at least add a “won't” fix tag to this thread to make it clear there is an issue (such a divergence _is_ an issue) which won't be fixed.

(*) By the way, this gave me the idea to perhaps create an Sass variant in the future (with another name, obviously, and not reusing any code from Sass).

**Comment by chriseppstein** [comment] 2016-01-12 18:29
> at least add a “won't” fix tag to this thread to make it clear there is an issue (such a divergence is an issue) which won't be fixed.

`WONTFIX`
