### ISSUE TITLE
style compressed, BOM and @font-face

### ISSUE THREAD

**Issue by dartess** [sass/sass#1983] opened 2016-02-04 01:41 UTC
style compressed and his BOM breaks first @font-face rule:
https://i.gyazo.com/075571ab196119ff877f24f9d2c63b33.png
https://i.gyazo.com/7043c4f2f0053a87a42b725e175e8fb9.png
with BOM my first rule with regular font not work

**Comment by chriseppstein** [comment] 2016-02-04 19:16
I actually don't know what this bug is about.

Please provide a sass file with no dependencies that reproduces this issue and what the expected output should be and how it's different from the actual output.

**Comment by chriseppstein** [comment] 2016-02-08 18:45
Closing due to nonresponsiveness.

**Closed as completed by chriseppstein** 2016-02-08 18:45 UTC
Labels: needs info

**Comment by krom** [comment] 2016-02-17 16:26
The problem appears if the original file contains UTF-8 characters

```
$cat file.scss 
div {
    content:"©";
}
```

Command
`scss file.scss file.css
`

Result files is

```
file.css:     UTF-8 Unicode text
file.css.map: ASCII text
file.scss:    UTF-8 Unicode text
```

Command
`scss -t compressed file.scss file.css`

Result files is

```
file.css:     UTF-8 Unicode (with BOM) text
file.css.map: ASCII text
file.scss:    UTF-8 Unicode text
```
