### ISSUE TITLE
Setting SASS variables inside a loop

### ISSUE THREAD

**Issue by wouter-muller** [sass/sass#2047] opened 2016-05-04 09:14 UTC
I am having problems putting something like the following repetitive variable declarations inside a loop:

```
$px1: 1px;
$px2: 2px;
$px3: 3px;
$px4: 4px;
$px5: 5px;
...
```

I thought i could just do this:

```
@for $i from 1 through 10 {
  $px#{$i}: #{$i}px;
}
```

But SCSS is complaining that it is invalid CSS, but i am not trying to write CSS, i am just trying to set some variables that i can use later on. 

Is there a way to set variables dynamically like this, without declaring any CSS?

**Comment by michalweiser** [comment] 2016-05-04 11:54
There is no way to interpolate variable name in SCSS, this is the reason why $px#{$i} is now working.

**Comment by cimmanon** [comment] 2016-05-04 11:56
Duplicate of https://github.com/sass/sass/issues/132

**Comment by xzyfer** [comment] 2016-05-04 11:59
To do this you need a list

``` sass
$pxs: ();
@for $i from 1 through 10 {
  $pxs: append($pxs, $i * 1px);
}

```

Now you can access you px via `nth`

``` sass
a {
  border-width: nth($pxs, 1); // 1px
}

```

**Comment by davidkpiano** [comment] 2016-05-04 12:02
^ Was just about to post what @xzyfer said, haha. Except, you should probably use `$i * 1px` instead of `#{$i}px` so it's an actual length value and not a string.

**Comment by xzyfer** [comment] 2016-05-04 12:03
@davidkpiano makes sense, updated.

**Comment by wouter-muller** [comment] 2016-05-04 12:15
OK, thanks guys!

@xzyfer Interesting example with the list!

I will only need a handful of these variables, so i'll just write them out without a loop...

**Closed as completed** 2016-05-04 18:47 UTC
