### ISSUE TITLE
Extending a selector/placeholder two times doesn't work

### ISSUE THREAD

**Issue by Sorendil** [sass/sass#2033] opened 2016-04-14 19:09 UTC
Hello,

Since 2 days, i'm searching for why my extend doesn't work. I didn't find any reply so i'm opening a new issue.

I finally found why but I can't explain it.

From my project, I have 2 components, as showed here : https://gist.github.com/Sorendil/a205bffb40addffd5678d40abb376582

But first, some explanations.

In cards actions (file card.scss line 7), I want all buttons to have the button style "hollow".
This works.

In cards images (file card.scss line 12), I want all elements to have a text-shadow (placeholder defined in another file)

BUT, in cards actions that are within card image (file card.scss line 18), I don't want buttons to have the button style "hollow" but the button style "transparent".

This doesn't work. After a lot of tests, I found that it's because I have two lines that extends %transparent.

To solve the problem, I just need to comment the line 18 (file card.scss) and uncomment the line 19 (card.scss). Since $transparent2 also include transparent buttons, it works !

So, my question is : Why do I need to use 2 placeholders with différent names even if they do totally the same thing ? 

Thanks in advance,
Anthony.

**Comment by cimmanon** [comment] 2016-04-14 19:11
Duplicate of https://github.com/sass/sass/issues/1596

**Comment by chriseppstein** [comment] 2016-04-14 21:46
Hi, I spent 10 minutes trying to understand this issue and failed. So maybe you can simplify your code down to the smallest possible amount of code that represents the issue you are having and not omit any code that you are having in your example (E.g. these are mixins that are never invoked in this code example and there are mixins used in the code example that are not defined.) I need to be able to run the minimal code example you give me and I need you to tell me what output you were expecting.

**Comment by Sorendil** [comment] 2016-04-15 12:29
Hi, 

Thanks for the response ! You're right, my example was not minimal. After some tests, I reproduce the bug with this code :

https://gist.github.com/Sorendil/ac0ea8261843a3980ddb3cd4527aa175

Same way that in my first code, you have to comment either the line 36 or 37.

In the first test, 
`.card .card_image .actions .button:hover {
  color: grey;
}` is never generated so my CSS fallback to `.card .actions .button:hover {
  color: #222222;
}`

The expected result is the second test, named test2.css in gist.

Sorry for not being clear the first time, I hope it's better now !

Thanks in advance,
Anthony.

**Comment by davidkpiano** [comment] 2016-04-15 13:19
You're probably not getting the expected results because (and correct me if I'm wrong @nex3) `@extend` tries to match the specificity of the extendee. That probably results in the simplification of the output selector.

**Comment by Sorendil** [comment] 2016-04-15 13:31
Probably, I don't know SASS enough to understand why the output in first test is optimized...

If you're right, how could I get around the problem ?

On my project, I have a mixin for card and a mixin for button. Since the selector is passed as an argument for both mixins, my card mixin doesn't know the button selector.

So I wanted to tell that all my buttons in `.card .card_image .actions {@extend %transparent; }` to extend the transparent style (transparent styles are used by buttons, titles, etc.)

Is there another way to do this ? I tried a lot of things without success.
Or maybe I don't use placeholders the right way ?

**Comment by nex3** [comment] 2016-04-15 19:34
> You're probably not getting the expected results because (and correct me if I'm wrong @nex3) `@extend` tries to match the specificity of the extendee. That probably results in the simplification of the output selector.

This isn't quite right. For every extending selector, `@extend` guarantees that the generated selector will contain at least one complex selector with two properties:
1. the complex selector matches all elements that are matched by the extending selector, and
2. the complex selector has specificity greater than or equal to the extending selector.

It's possible for those two properties to be satisfied without literally including the extending selector in the output, in which case the original selector will be omitted. This can look strange, but it shouldn't affect the actual rendering of the page unless you're relying on the generated selector having even greater specificity than the extending selector, which is not safe—and not something we could guarantee even if we produced every element of the combinatorial explosion of possible selectors we could generate.

**Closed as completed** 2016-04-18 18:16 UTC
