### ISSUE TITLE
Variable in nested rule leaks to parent rule

### ISSUE THREAD

**Issue by Marat-Tanalin** [sass/sass#1767] opened 2015-07-10 16:47 UTC
Testcase:

```
BODY {
    $bg: green;

    DIV {
        $bg: red;
    }

    background: $bg;
}
```

Actual result (tested with SassMeister):

```
BODY {
    background: red;
}
```

Expected result:

```
BODY {
    background: green;
}
```

The current actual result looks contradicting with the official SASS [documentation](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#variables_):

> Variables are only available within the level of nested selectors where they’re defined.

Nested-rule variable is a _local_ variable that should just _shadow_ parent-rule variable of the same name (so that parent-rule variable is not accessible in nested rule), but in no way _alter_ it.

Code where variable is used _before_ nested rule works as expected:

```
BODY {
    $bg: green;

    background: $bg;

    DIV {
        $bg: red;
    }
}
```

**Comment by nex3** [comment] 2015-07-10 18:54
This is working as intended. In Sass, when you declare a variable (that is, assign it a value for the first time), that variable becomes visible in the scope it was declared _and all nested scopes_. Any assignment to a variable name in a scope where a variable with that name is already visible will assign to the visible variable rather than declaring a new one. The only exception to this is global variables; an assignment to a local variable with the same name as a global will create a new scope unless `!global` is used.

**Closed as completed by nex3** 2015-07-10 18:54 UTC

**Comment by Marat-Tanalin** [comment] 2015-07-10 19:06
Thanks. Could you explain what's the _exact practical point_ of being able to _alter_ parent-rule variable by an assignment in a nested rule?

It's perfectly reasonable and usable that parent-rule variable is available in all nested rules, but why is it possible to _alter_ parent-rule variable?

Currently it turns out that if I move some rule to another rule, it may easily break the latter one just due to unexpected variable-name collision.

**Comment by nex3** [comment] 2015-07-10 20:46
It's important because it makes variable scoping work the same for all blocks that look the same, and the same as in most C-like languages.

**Comment by Marat-Tanalin** [comment] 2015-07-12 09:08
> it makes variable scoping work the same for all blocks that look the same

It's not clear what this means. Could you be more specific?

> and the same as in most C-like languages.

CSS is a declarative language, not a programming one. Similarities with programming languages are typically considered irrelevant in CSS-related discussions (and SCSS as a preprocessor has much more in common with CSS than with programming languages).

I have experience in JS, PHP, and C++, and I'm a web developer since 2002, but this behavior is still unexpected for me from **CSS** perspective. It's like if setting background for `UL > LI` would affect background of `UL` — totally unexpected and literally confusing. CSS variables (currently implemented in Gecko) do not allow this as well: they can be overridden solely top down, not bottom-up.

What is the usecase for **altering** parent-rule variable by a declaration inside a nested rule?

**Comment by nex3** [comment] 2015-07-17 21:15
> It's not clear what this means. Could you be more specific?

It's clearly the case that a variable declared outside of, say, an `@if` or a `@function` should be assignable from within that block. Nested rules look the same, so they work the same way.

> CSS is a declarative language, not a programming one. Similarities with programming languages are typically considered irrelevant in CSS-related discussions (and SCSS as a preprocessor has much more in common with CSS than with programming languages).
> 
> I have experience in JS, PHP, and C++, and I'm a web developer since 2002, but this behavior is still unexpected for me from **CSS** perspective. It's like if setting background for `UL > LI` would affect background of `UL` — totally unexpected and literally confusing. CSS variables (currently implemented in Gecko) do not allow this as well: they can be overridden solely top down, not bottom-up.
> 
> What is the usecase for **altering** parent-rule variable by a declaration inside a nested rule?

Sass is not CSS, and Sass variables are _very much_ not CSS variables. In fact, the reason the syntax for CSS variables is so different than that for Sass variables is to reflect the difference in semantics: the CSS folks wanted people to understand visually that the cascading nature of CSS variables were distinct from the procedural nature of preprocessor variables.

Programming languages are very relevant to Sass's design, precisely because Sass brings various programming conventions into the world of CSS. There's no way we could implement variables with the same semantics as CSS variables; we don't have the document context necessary to make that work. Given that, it makes a lot of sense to implement them with the same semantics as the popular languages whose semantics Sass is importing.
