### ISSUE TITLE
Polymer mixin syntax is incompatible with Sass

### ISSUE THREAD

**Issue by voondo** [sass/sass#1832] opened 2015-09-10 12:25 UTC
From https://github.com/Polymer/polymer/issues/1373: 

Running the following through the Sass compiler:

```
:host {
  --my-toolbar-theme: {
    background-color: green;
    border-radius: 4px;
    border: 1px solid gray;
  }
}
```

Results in:

```
:host {
  --my-toolbar-theme-background-color: green;
  --my-toolbar-theme-border-radius: 4px;
  --my-toolbar-theme-border: 1px solid gray;
}
```

Which is obviously unwanted.

Reference: https://www.polymer-project.org/1.0/docs/devguide/styling.html#custom-css-mixins

**Comment by mprins** [comment] 2015-09-10 16:46
--my-toolbar-theme is not a valid selector, so it's not handled as such, you need to escape it in scss to get what you want:

``` scss
--my-toolbar-theme: #{'{
    background-color: green;
    border-radius: 4px;
    border: 1px solid gray;
}'};
```

see also
-  #1128
- http://www.w3.org/TR/css3-selectors/#w3cselgrammar

**Comment by voondo** [comment] 2015-09-10 17:39
Indeed... so I guess Polymer goes in the wrong direction.
Anyway, thanks for the workaround !

**Comment by voondo** [comment] 2015-09-11 08:54
From https://github.com/Polymer/polymer/issues/1373#issuecomment-139331595:
"Note --my-toolbar-theme: is how you define a custom property. If the sass compiler can't handle that syntax, then it's a bug. Properties are landing in Chrome and already in FF."

**Comment by nex3** [comment] 2015-09-11 21:53
Duplicate of #1128.

**Closed as completed by nex3** 2015-09-11 21:53 UTC

**Comment by lozandier** [comment] 2015-10-05 12:09
@voondo Hi, it's grossly inaccurate Polymer is going in the wrong direction with this. This capability of Polymer was supervised by an established CSS spec writer that was already planning to have this functionality be standardized which it has since its widespread use in the Polymer project: http://tabatkins.github.io/specs/css-apply-rule/

This functionality  are _custom property sets & css properties_ rather than selectors, so I'd also ignore the outdated reference above by @mprins (CSS custom properties beyond the vendor prefixes didn't exist in 2011). 

Perhaps they are a officially a subset of selectors, but that's an outdated reference nonetheless unless you're referring to how Sass is maybe interpreting it as such because it may lack the understanding of  such property sets

**Comment by lozandier** [comment] 2015-10-05 12:46
@voondo Feel free to ping the Polymer Slack community about this.
