### ISSUE TITLE
Versions v1.42.x broken (and maybe other previous ones...)

### ISSUE THREAD

**Issue by jeanlescure** [sass/sass#3164] opened 2021-09-26 01:55 UTC
Our team had to downgrade back to `1.38.2` because latest versions are reporting errors that were not errors before:

![2021-09-25_19-47](https://user-images.githubusercontent.com/3330339/134790456-b5fb7a5b-bdf0-4819-910e-bde58fc54e8b.png)

The previous error happenes both with `v1.42.1` and `1.42.0`. Since this was affecting a time-sensitive deployment I simply switched `^1.38.2` to `1.38.2` on our `package.json` to revert to the last known stable version (to our knowledge).

NOTE: I think semantic-ui is using the syntax `--0.05rem - 1.2em` because what they mean is `-(-0.05rem - 1.2em)`, as in flipping the negative to positive or viceversa. Either way this detail is mostly irrelevant to the issue. The real issue is that something that used to work is now broken, and downgrading to a previous version fixes the problem.

**Comment by stof** [comment] 2021-09-28 10:48
@nex3 this one is a duplicate of https://github.com/sass/dart-sass/issues/1512 (where it has been discussed)

**Closed as completed** 2021-09-28 11:38 UTC
