### ISSUE TITLE
-(50px/2)

### ISSUE THREAD

**Issue by perfey** [sass/sass#1915] opened 2015-11-26 11:20 UTC
sass
background: url(../img/xxx.png) no-repeat -(50px/2) 0;
to css
background: url(../img/xxx.png) no-repeat-25px 0;

error, loss of space. The following is correct:
background: url(../img/xxx.png) no-repeat -25px 0;

**Comment by cimmanon** [comment] 2015-11-26 15:55
Duplicate of https://github.com/sass/sass/issues/1912

**Comment by chriseppstein** [comment] 2015-12-01 21:32
Please see my comment on #1912

**Closed as completed by chriseppstein** 2015-12-01 21:32 UTC
