### ISSUE TITLE
Slotted name and class selectors

### ISSUE THREAD

**Issue by priley86** [sass/sass#2379] opened 2017-09-26 19:26 UTC
I've noted that using Sass v4.0.0 alpha on Sassmeister does not yet support slotted name and slotted class selectors...

https://gist.github.com/priley86/e972837f49c946d0c5f02fff6e60f338

```Invalid CSS after "::slotted(": expected pseudo_expr, was "[slot='descript..."```

Any idea when you'll add this for full support of Shadow DOM CSS selectors? More on those here...
https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-slotted-content-distributed-children

**Comment by nex3** [comment] 2017-09-29 23:09
Duplicate of #2325.

**Closed as completed by nex3** 2017-09-29 23:09 UTC

**Comment by priley86** [comment] 2017-09-30 02:30
@nex3 after testing this again in 3.5.0.beta2 on Sassmesiter, this appears to work. However 4.0.0.alpha1 does not. It just seems this has not made into the alpha branch for some reason.

**Comment by nex3** [comment] 2017-10-07 01:18
There hasn't been a recent alpha release in a while, which is probably why.
