### ISSUE TITLE
Invalid output with missing semicolon

### ISSUE THREAD

**Issue by royaldark** [sass/sass#1764] opened 2015-07-07 22:14 UTC
I was tracking down a missing `img` selector when I realized that I was missing a semicolon in one of my statements. However, despite the unterminated statement, it compiles successfully, outputting invalid CSS. 

Input:

``` sass
$AVATAR_SIZE: 50px;

.main {
    .avatar {
        width: $AVATAR_SIZE;
        height: $AVATAR_SIZE

        img {
            width: $AVATAR_SIZE;
        }
    }
}
```

Output:

``` css
.main .avatar {
  width: 50px;
  height: 50px img;
    height-width: 50px; }
```

Version info:

```
$ sass -v
Sass 3.4.6 (Selective Steve)
$ ruby -v
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
$ uname -a
Linux joe-asus 3.16.0-31-generic #43-Ubuntu SMP Tue Mar 10 17:37:36 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by cimmanon** [comment] 2015-07-07 22:56
Duplicate of https://github.com/sass/sass/issues/1588

**Closed as completed** 2015-07-10 18:24 UTC
