### ISSUE TITLE
Units of numbers equal to 0

### ISSUE THREAD

**Issue by veronQ** [sass/sass#2556] opened 2018-08-31 21:25 UTC
``` scss
@mixin test($value) {
  @if $value == 0 {
    color: blue;
  }
}

.foo {
  @include test(0k);
}

```

Expected result shouldn't be *true*.

(I am using Ruby sass)

**Comment by nex3** [comment] 2018-08-31 21:30
Duplicate of #1496. FYI, this is fixed in Dart Sass.

**Closed as completed by nex3** 2018-08-31 21:30 UTC
