### ISSUE TITLE
mixin shorthand syntax

### ISSUE THREAD

**Issue by geddski** [sass/sass#1579] opened 2015-01-03 00:55 UTC
When using a lot of mixins your code becomes cluttered with `@include`s. It would be really awesome to be able to have a shorthand syntax for mixins:

``` scss
@component(menu) {
  ...
}
```

as a shorthand for the full syntax: 

``` scss
@include component(menu) {
  ...
}
```

This would make using something like csstyle that relies on mixins a lot cleaner.

**Comment by cimmanon** [comment] 2015-01-03 11:58
Duplicate of https://github.com/sass/sass/issues/366

**Closed as completed** 2015-01-06 16:45 UTC
