### ISSUE TITLE
Using @use when @import is discouraged.

### ISSUE THREAD

**Issue by HowdyMcGee** [sass/sass#2890] opened 2020-08-11 23:25 UTC
Let me start off by saying that I am 100% new to Sass and preprocessors in general. Full disclosure, I did create a [SO Question](https://stackoverflow.com/questions/63361377/undefined-font-awesome-variable-when-use).

Looking at the docs it says that `@import` is discouraged so I've been using `@use` throughout a Laravel project I've been working on. The problem occurs when I want to add a dependency like Font Awesome to my project.

The short of it is that I can `@import` Font Awesome from my node_modules folder successfully.

```
@import "~@fortawesome/fontawesome-free/scss/fontawesome.scss";
@import "~@fortawesome/fontawesome-free/scss/solid.scss";

.add-new {
    &:before {
        @include fa-icon;
        content: fa-content( $fa-var-plus );
    }
}
```

The above works. If I convert it over to a `@use` directive though I get continuous errors.

```
@use "~@fortawesome/fontawesome-free/scss/fontawesome.scss" as *;
@use "~@fortawesome/fontawesome-free/scss/solid.scss" as *;

.add-new {
    &:before {
        @include fa-icon;
        content: fa-content( $fa-var-plus );
    }
}
```

I'm not sure if I'm doing something wrong or if I simply cannot use the `@use` directive when working with other assets that use `@import` ( as fontawesome.scss imports many other assets ). Another issue that came to mind is that I'll likely be using Font Awesome throughout my project in various places. Having to remove to `@use` these two lines in every file I need icons seems cumbersome, like I'm missing something or doing something wrong.

I'm hoping someone can clarify what I'm doing wrong and maybe get advice on how others are solving this kind of issue.

**Comment by Awjin** [comment] 2020-08-13 21:25
It looks like Miriam addressed your questions on StackOverflow. Closing this as a duplicate of the conversation there.

**Closed as completed by Awjin** 2020-08-13 21:25 UTC

**Comment by HowdyMcGee** [comment] 2020-08-14 13:38
@Awjin Miriam did address my question but that did not solve my problem. If you read the answer Miriam suggests ( but did not test ) using `@forward` to fix this issue. I've tried that and I cannot use `@forward` because the two necessary files import the same group of variables, and as my comment on that answer suggest, I get a duplicate variables errors.

So I cannot `@use` and I cannot `@forward`, this is not a solved issue regardless if my SO question and the problem is rooted in this libraries use of `@import` as far as I can tell.

**Comment by HowdyMcGee** [comment] 2020-08-16 17:08
I guess, but at the moment there's not really a good workaround to be compatible with these NPM libraries that use `@import`. In the mentioned project I **had** to switch my convention away from `@use` to  `@import` simply because there was no workable solution that I could find. As mentioned in the comment to the provided answer, I could not use `@use` because the library uses `@import` to bring in other files. I could not use `@forward` because of duplicate variables issues in regards to its use of `@import`.

Surely Font Awesome is not the only library where this is an issue, right?

I think moving away from `@import` is a fine choice but I'm not sure libraries are ready for it which unfortunately means my projects won't be ready for it. In any case, I've [opened an issue with the Font Awesome library](https://github.com/FortAwesome/font-awesome-sass/issues/195) but I'm not holding my breath.

**Comment by mirisuzanne** [comment] 2020-08-16 17:27
@HowdyMcGee I think with a little finesse to the `@forward` rules, you can clear up the conflict. I added details on SO.
