### ISSUE TITLE
Custom variable interpolation does not work in @each

### ISSUE THREAD

**Issue by glebm** [sass/sass#2386] opened 2017-10-12 19:42 UTC
Given the following scss file ([_root.scss](https://github.com/twbs/bootstrap/blob/c8ee8509cb72edd2f758398664bed8a0eeeb2dc4/scss/_root.scss)):

```scss
:root {
  @each $color, $value in $colors {
    --#{$color}: $value;
  }

  @each $color, $value in $theme-colors {
    --#{$color}: $value;
  }

  @each $bp, $value in $grid-breakpoints {
    --breakpoint-#{$bp}: $value;
  }

  --font-family-sans-serif: $font-family-sans-serif;
  --font-family-monospace: $font-family-monospace;
}
```

Sass throws the following syntax error:

```
Error: Invalid CSS after "...$color}: $value": expected "{", was ";"
        on line 3 of /home/glebm/repos/twbs/bootstrap-rubygem/assets/stylesheets/bootstrap/_root.scss
        from line 11 of /home/glebm/repos/twbs/bootstrap-rubygem/assets/stylesheets/_bootstrap.scss
        from line 4 of /home/glebm/repos/twbs/bootstrap-rubygem/tmp/new-compass-project/sass/styles.scss

1: :root {
2:   @each $color, $value in $colors {
3:     --#{$color}: $value;
4:   }
5: 
6:   @each $color, $value in $theme-colors {
7:     --#{$color}: $value;
8:   }

Backtrace:
/home/glebm/repos/twbs/bootstrap-rubygem/assets/stylesheets/bootstrap/_root.scss:3
/home/glebm/repos/twbs/bootstrap-rubygem/assets/stylesheets/_bootstrap.scss:11
/home/glebm/repos/twbs/bootstrap-rubygem/tmp/new-compass-project/sass/styles.scss:4
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:1207:in `expected'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:1137:in `expected'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:1132:in `tok!'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:665:in `block'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:735:in `declaration_or_ruleset'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:685:in `block_child'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:674:in `block_contents'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:666:in `block'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:307:in `each_directive'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:222:in `special_directive'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:197:in `directive'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:685:in `block_child'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:674:in `block_contents'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:666:in `block'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:658:in `ruleset'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:684:in `block_child'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:674:in `block_contents'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:125:in `stylesheet'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:41:in `parse'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/engine.rb:409:in `_to_tree'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/engine.rb:315:in `to_tree'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:327:in `block in visit_import'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:88:in `block in with_import'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:115:in `with_frame'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:88:in `with_import'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:79:in `block in with_base'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:115:in `with_frame'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:79:in `with_base'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `visit'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:329:in `block (2 levels) in visit_import'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:329:in `map'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:329:in `block in visit_import'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:88:in `block in with_import'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:115:in `with_frame'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:88:in `with_import'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:326:in `visit_import'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:79:in `block in with_base'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:115:in `with_frame'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/stack.rb:79:in `with_base'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `visit'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `map'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:170:in `visit_children'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:190:in `visit_root'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:161:in `visit'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:10:in `visit'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/root_node.rb:36:in `css_tree'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/tree/root_node.rb:20:in `render'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/engine.rb:284:in `render'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:17:in `block in render'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:29:in `with_import_scope'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:16:in `render'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/plugin/compiler.rb:494:in `update_stylesheet'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/plugin/compiler.rb:215:in `block in update_stylesheets'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/plugin/compiler.rb:209:in `each'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/sass-3.4.25/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-1.0.3/lib/compass/sass_compiler.rb:40:in `compile!'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-1.0.3/lib/compass/commands/update_project.rb:49:in `perform'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-1.0.3/lib/compass/commands/stamp_pattern.rb:76:in `perform'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-1.0.3/lib/compass/commands/base.rb:18:in `execute'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-1.0.3/lib/compass/commands/project_base.rb:19:in `execute'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-1.0.3/lib/compass/exec/sub_command_ui.rb:15:in `run!'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-1.0.3/bin/compass:30:in `block in <top (required)>'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/gems/compass-1.0.3/bin/compass:44:in `<top (required)>'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/bin/compass:23:in `load'
/home/glebm/repos/twbs/bootstrap-rubygem/.bundle/ruby/2.4.0/bin/compass:23:in `<main>'
```

**Comment by nex3** [comment] 2017-10-12 21:03
Duplicate of #2383.

**Closed as completed by nex3** 2017-10-12 21:03 UTC
