### ISSUE TITLE
Silent classes with BEM

### ISSUE THREAD

**Issue by morriq** [sass/sass#2523] opened 2018-05-16 19:36 UTC
Hello.

```
%form-control--invalid {
  %form-control__label {
    color: red;
  }
}

%form-control {
  min-height: 60px;

  %form-control__label {
    transform: translateY(-32px);
  }
}

.form-control {
  @extend %form-control;

  & &__label {
    @extend %form-control__label;
  }

  &--invalid {
    @extend %form-control--invalid;
  }
}
```

compiles into

```
.form-control--invalid .form-control .form-control__label, .form-control .form-control--invalid .form-control__label {
  color: red;
}

.form-control {
  min-height: 60px;
}
.form-control .form-control__label {
  transform: translateY(-32px);
}
```

I don't understand why this compiled first class looks like above. Is it by design? I want to achieve `.form-control--invalid.form-control .form-control__label`

**Comment by chriseppstein** [comment] 2018-05-16 19:46
Duplicate of https://github.com/sass/sass/issues/2262

**Closed as completed by chriseppstein** 2018-05-16 19:46 UTC
