### ISSUE TITLE
Feature request: inline sourcemap as Data URI

### ISSUE THREAD

**Issue by nazar-pc** [sass/sass#2068] opened 2016-05-26 07:27 UTC
I was surprised by `--sourcemap=inline`, since it actually includes source into map, but not map into source.
What do you think about having option for embedding sourcemap into resulting CSS?

My use case is that generally my Apache and Nginx configs only allow css/js/fonts//images files to be accessible from the web, but not scss/ls/map files.
So having source map bundled with CSS seems really convenient (comments are stripped in production mode anyway).

In LiveScript this kind of source map is called `embedded`.

**Comment by chriseppstein** [comment] 2016-06-02 21:05
Is there a reason why you can't change your config to make your source map files available?

**Comment by nazar-pc** [comment] 2016-06-02 21:57
Obviously, it is technically possible, but there are 2 files already: source and compiled, and I'd like to avoid having third one for each source.

**Comment by chriseppstein** [comment] 2016-06-02 22:05
I'm not opposed to adding another sourcemap output type. But we have much bigger issues on our plate right now so if someone makes a pull request against the `next` branch. we will accept it after code review.

**Comment by nex3** [comment] 2018-04-06 21:27
Duplicate of sass/ruby-sass#25

**Closed as completed by nex3** 2018-04-06 21:27 UTC
Labels: enhancement, help wanted
