### ISSUE TITLE
[FEATURE REQUEST] property chaining

### ISSUE THREAD

**Issue by SuperDJ** [sass/sass#2133] opened 2016-09-02 13:33 UTC
Write one line of properties and give them the same value for example:

```
line-height, height: 14px;
```

Making it:

```
line-height: 14px;
height: 14px;
```

Or

```
width, height, border-radius: 20px;
```

Making it:

```
width: 20px;
height: 20px;
border-radius: 20px;
```

**Comment by chriseppstein** [comment] 2016-09-08 18:02
Duplicate of #109

**Closed as completed by chriseppstein** 2016-09-08 18:02 UTC
