### ISSUE TITLE
🛑 [BUG] `:is(&)` ⇒ compiling BUT `:where(&)` don't

### ISSUE THREAD

**Issue by nitin2953** [sass/sass#3270] opened 2022-03-12 16:09 UTC
SCSS
```scss
main {
   background-color: yellow;

  :is(& > *) {
     background-color: blue;
  }

  :where(& > *) {
     background-color: red;
  }
}
```

Compiled CSS
```css
main {
   background-color: yellow;
}

:is(main > *) {
   background-color: blue;
}

main :where(& > *) {
   background-color: red;
}
```

Using `"sass": "^1.49.8"`

**Comment by stof** [comment] 2022-03-14 11:49
duplicate of https://github.com/sass/sass/issues/3130

**Closed as completed** 2022-03-14 14:25 UTC
