### ISSUE TITLE
sass changing end of line sequence after compiling

### ISSUE THREAD

**Issue by KunalTanwar11** [sass/sass#3353] opened 2022-07-06 13:26 UTC
My default encoding is `CRLF` as I am using windows but after compiling the **EOL** is converting into `LF`

**command**
`sass input.scss --no-source-map -s compressed output.css`

I am using javascript version of sass which I installed using `yarn add -D sass` not the native `dart` version.

**Comment by nex3** [comment] 2022-07-06 20:27
Duplicate of #2604

**Closed as not planned by nex3** 2022-07-06 20:27 UTC
