### ISSUE TITLE
Confusing variable scope in blocks - bug?

### ISSUE THREAD

**Issue by wheresrhys** [sass/sass#2082] opened 2016-06-15 09:25 UTC
If a variable is used in an `@if` block its scope behaves differently depending on whether or not the variable already exists in an outer/the global scope.
- if it exists in an outer scope then the variable references the one in the outer scope
- if it doesn't exist then a new local variable is created

http://www.sassmeister.com/gist/dd6ef43ddeefc4fa499b5b43daaca5da

Which is confusing, and leads to hard to track down bugs, as the variable in the global scope may be defined in a different file.

I can't find this behaviour documented anywhere. Is it a bug or expected behaviour that should be documented?

**Comment by chriseppstein** [comment] 2016-06-15 20:05
@wheresrhys that url is a 404 for me.

However, the block of an `@if` or `@else` follow the same scoping rules as every other conditional block and loop. These are "semi-global" scopes. The follow slightly different scoping rules when used directly in the global scope (as opposed to when they are used in the local scope of a function, mixin, or selector). This is by design because conditionals and loops are frequently used to initialize global variables and forcing them to add `!global` to set a global variable in that context seems cumbersome.

I think you're right that this specific behavior is undocumented in the language reference. We should document it better.

> Which is confusing, and leads to hard to track down bugs, as the variable in the global scope may be defined in a different file.

This is, more generally, a problem with global variables in Sass, independent of whether they are used in a conditional. Specifically in Sass 4.0 our module system will scope global variables to the module and provide syntax for avoiding unintended name collisions across modules.

**Comment by malacca** [comment] 2017-06-07 11:35
variable scope problem
test on  Sass v4.0.0.alpha.1

scss

    $color:red;
    div {
        $color: blue;
        h1 {
            $color: green;
            color: $color;
        }
        color: $color;
    }
    .outer {
      color:$color;
    }

output css


    div {
      color: green;
    }
    div h1 {
      color: green;
    }
    .out {
      color: red;
    }

i think it will be


    div {
      color: blue;
    }
    div h1 {
      color: green;
    }
    .out {
      color: red;
    }

is me wrong? or this is bug

**Comment by malacca** [comment] 2017-06-07 13:00
test @mixin scope by same way

scss

    @mixin call {a: b}
    
    foo {
      @mixin call {c: d}
      bar {
        @mixin call {m: n}
        @include call;
      }
      @include call;
    }
    
    baz {@include call}


output css

    foo {
      c: d;
    }
    foo bar {
      m: n;
    }
    baz {
      a: b;
    }

relative to variable scope, it looks right, confusing :)

**Comment by nex3** [comment] 2019-04-05 05:28
Closing this out; it's covered by the new reference docs on the Sass site.

**Closed as completed by nex3** 2019-04-05 05:28 UTC
