### ISSUE TITLE
CSS pass by ref-like variables

### ISSUE THREAD

**Issue by samdesota** [sass/sass#1770] opened 2015-07-11 00:13 UTC
Hey Guys,

I recently read up on CSS Variables. One thing I noticed is that they are significantly more useful than sass variables.

Let's say you use a CSS Variable to set a variable called bodyWidth. You can use this variable anywhere in your code without containing the entire document and preventing full width items. Whenever you need something to be body width, you simply apply the variable. You can do the same with sass, except you can't change body width inside media queries. Here's a working example with CSS Variables(You need to be in FF31+): http://jsfiddle.net/tjfcu5g8/2

Resize the content container.

Obviously you don't want change the entire variable scoping method, just ones with the `--var` syntax so we have support until it is supported on more browsers.

Edit: Updated fiddle.

**Comment by cimmanon** [comment] 2015-07-11 00:46
Duplicate of https://github.com/sass/sass/issues/340 and https://github.com/sass/sass/issues/1227 (and probably others)

**Closed as completed** 2015-07-17 20:55 UTC
