### ISSUE TITLE
Get property value from parent selector

### ISSUE THREAD

**Issue by afonsomatos** [sass/sass#1759] opened 2015-06-29 13:10 UTC
Is this possible?

``` css
.parent {
    height: 20px;
    .child {
        height: parent(height) / 2;
    }
}
```

**Comment by davidkpiano** [comment] 2015-06-29 13:13
Unfortunately (well, for very good reasons), it's not possible. Use variables:

``` scss
.parent {
  $parent-height: 20px;
  height: $parent-height;
  .child {
    height: $parent-height / 2;
  }
}
```

**Comment by cimmanon** [comment] 2015-06-29 13:16
Duplicate of https://github.com/sass/sass/issues/521

**Closed as completed** 2015-06-29 19:06 UTC

**Comment by ungular** [comment] 2016-11-17 15:24
sass: what value will come in child if  `$parent-height: 100%` ?

**Comment by snarlynarwhal** [comment] 2017-08-29 22:59
Stylus has this feature, I recommend checking that out.
