### ISSUE TITLE
Feature request: extend & class with element name

### ISSUE THREAD

**Issue by thany** [sass/sass#2536] opened 2018-07-09 10:18 UTC
I'd like to be able to do something like this:
```scss
.filters {
    label.& { ... }
    p.& { ... }
}
```
Which would compile to:
```css
label.filters { ... }
p.filters { ... }
```
There is probably a huge can of worms in here somewhere, but it boils down to being able to prepend `&` with an element name. It's not all that weird when you consider that *appending* something is already possible, but *prepending* isn't (or so it seems).

One workaround Ive found is pretty convoluted, and I might be overthinking it:
```scss
.filters{
    @at-root #{selector-append(label,&)} { ... }
    @at-root #{selector-append(p,&)} { ... }
}
```
The `@at-root` in my particular case works, but it won't when `.filters` from my example is nested yet again in something. If I don't put `@at-root` it will still prepend `.filters ` even though `&` is used already.

**Comment by nex3** [comment] 2018-07-10 00:04
Duplicate of #1425 

You can work around this a little more simply like so:

```scss
.filters{
    @at-root label#{&} { ... }
    @at-root p#{&} { ... }
}
```

You could also encapsulate this in a mixin:

```scss
@mixin append-parent($selector) {
  @at-root #{$selector}#{&} {@content}
}

.filters{
    @include append-parent("label") { ... }
    @include append-parent("p") { ... }
}
```

**Closed as completed by nex3** 2018-07-10 00:04 UTC
