### ISSUE TITLE
Adding new built in function - raw

### ISSUE THREAD

**Issue by jcoc611** [sass/sass#1771] opened 2015-07-11 01:14 UTC
While using SASS, I came across a very interesting bug where I needed to output a character code in the compiled CSS (for example: `content: '\f123'`). The issue was that this was being converted into `content: 'x'`, where _x_ was the actual character. Something like issue #1663.

This particular issue might be overcome by some hacks using mixins and variables; however, I feel like there should be a function that outputs _exactly_ something. It would look like this:

``` sass
selector {
    content: raw('\f123');
}
```

And it would leave every character as is. I feel like this could solve some potential frustrations for people. I've felt the general consensus, however, that such a function would be a _bad idea_. I wan't to know _why_ though.

If it turns out that the problems with this function can be overcome, I could build it and create a pull request.

**Comment by cimmanon** [comment] 2015-07-11 12:16
Duplicate of https://github.com/sass/sass/issues/1395

**Comment by nex3** [comment] 2015-07-17 21:02
This function doesn't really even make sense. There's nothing that the `raw()` function could return that would be in any way different from its input. Sass (per the CSS spec) treats escapes identically to the raw characters they represent, so the string produced by `'\f123'` contains a single character, U+F123, "". There's no distinction in Sass's object model between that string and one defined by literally writing `''` in the stylesheet.

Moreover, when converting to CSS, Sass's strings are converted to CSS strings _with the same contents_. This means that if you have a Sass string that contains the characters `\`, `f`, `1`, `2`, and `3`, its conversion to CSS will be `'\\f123'`, since that's a CSS string that has the same contents. So there's no sequence of characters that `raw()` could return that would produce the ouput you want.

**Closed as completed by nex3** 2015-07-17 21:02 UTC
