### ISSUE TITLE
Can anybody of the developers realize new helpful feature see code

### ISSUE THREAD

**Issue by nilsenj** [sass/sass#1621] opened 2015-02-03 16:20 UTC
@each $color in blue-grey, green, light-blue, light-blue, orange, red, lime, brown, amber, cyan, deep-orange, deep-purple, grey, light-green, light-blue, purple, teal, yellow, indigo, dark  {
    .#{$color} {
      @import "../../../color-schemas/#{$color}";
      @include block-variant($darkPrimaryColor, $primaryTextColor, $textPrimaryColor, $primaryColor, $lightPrimaryColor, $secondaryTextColor, $accentColor, $dividerColor);
    }
  }

the problem you already know the error output
sass import directives may not be used within control directives or mixins

**Comment by cimmanon** [comment] 2015-02-03 17:14
Duplicate of https://github.com/sass/sass/issues/739

**Closed as completed** 2015-02-04 18:13 UTC
