### ISSUE TITLE
Sass loop function for import files

### ISSUE THREAD

**Issue by nikhil-toobler** [sass/sass#2531] opened 2018-06-29 07:39 UTC
Any option to import multiple files using sass loop function. Here below my file tree structure.

```
/scss/ 
    /pages/
        /home/
            home.scss
            home-sm.scss
            home-md.scss
            home-lg.scss
        /about/
            about.scss
            about-sm.scss
            about-md.scss
            about-lg.scss
        /contact/
            contact.scss
            contact-sm.scss
            contact-md.scss
            contact-lg.scss
        pages.scss
```
And importing structure in **pages.scss** like below

```
//home
@import "home/home";
@import "home/home-xs";
@import "home/home-sm";
@import "home/home-md";
@import "home/home-lg";

//about
@import "about/about";
@import "about/about-xs";
@import "about/about-sm";
@import "about/about-md";
@import "about/about-lg";

//contact
@import "contact/contact";
@import "contact/contact-xs";
@import "contact/contact-sm";
@import "contact/contact-md";
@import "contact/contact-lg";
```
I want to reduce this `import` steps like using with sass function or anything.

**Note**: _I think using @import "scss/**/*" method is not a good deal for some cases like prioritized ordering files, overriding, etc._

**Comment by nex3** [comment] 2018-06-29 19:40
Duplicate of #739

**Closed as completed by nex3** 2018-06-29 19:40 UTC
