### ISSUE TITLE
Make it possible to define constants in SCSS

### ISSUE THREAD

**Issue by luiscla27** [sass/sass#3398] opened 2022-09-23 01:55 UTC
I think it would be great to be able to tell developers "this variable is a constant". [Benefits of using constants](https://www.campbellsci.com/blog/using-constants-crbasic) variables [are well known in many languages](https://realpython.com/python-constants/#why-use-constants). So, please consider it.

The suggested syntax would be the typescript assertion [`as const`](https://stackoverflow.com/a/66993671/1657465), something similar to this:
```scss
// with this `$red-flag` would be a constant and any means of trying to modify its value will result in an error. 
$red-flag: #ffb6c1 as const;
// or 
const $red-flag: #ffb6c1; /* however I think `as const` look best :) */
```
The reason I suggest this syntax is because `scss` is widely used in typescript projects (such as Angular), so at least in that niche it'll be really easy to remember.

For more context of my use-case, please take a look to [this stackoverflow question](https://stackoverflow.com/q/73807866/1657465).

**Comment by nex3** [comment] 2022-09-26 20:33
Duplicate of #3171.

**Closed as not planned by nex3** 2022-09-26 20:33 UTC
