### ISSUE TITLE
Proposal of defining the same value for several properties

### ISSUE THREAD

**Issue by long-lazuli** [sass/sass#1859] opened 2015-10-13 19:04 UTC
Like we can do for selectors in CSS :

``` SCSS
input, button { ... }
```

It would be excellent to be able to select many properties :

``` SCSS
.absolute {
  margin: auto;
  top, right, bottom, left: 0;
}
```

**Comment by cimmanon** [comment] 2015-10-13 19:05
Duplicate of https://github.com/sass/sass/issues/109

**Closed as completed** 2015-10-13 19:06 UTC

**Comment by long-lazuli** [comment] 2015-10-13 19:08
thx, I close this one.
