### ISSUE TITLE
& selector in SCSS and CSS behaves differently

### ISSUE THREAD

**Issue by FlorianBabel** [sass/sass#3809] opened 2024-03-14 14:10 UTC
The following code produces different results if used directly as CSS or as SCSS, that compiles to CSS.
```css
.level1 {
    .level3 {
        .level2 & {
            background: red;
        }
    }
}
``` 
---
If used as CSS it gets interpreted in the following way:
```css
.level1 .level2 .level3 {
   background: red;
}
``` 
https://codepen.io/flo02468/pen/WNWGOgO

---

If used as SCSS the resulting CSS looks like this:
```css
.level2 .level1 .level3 {
   background: red;
}
``` 
https://codepen.io/flo02468/pen/eYodRKr

---
I also attached two identical codepens that only differ in that on of them uses scss instead of css
Regardless of which case is better i think this is something to talk about.

**Comment by rkh** [comment] 2024-03-14 19:58
Related to #3030.

**Comment by nex3** [comment] 2024-03-15 02:13
Duplicate of #3030

**Closed as not planned by nex3** 2024-03-15 02:13 UTC
