### ISSUE TITLE
Color declaration values aren't compressed if terminated by a semicolon

### ISSUE THREAD

**Issue by xzyfer** [sass/sass#1946] opened 2015-12-28 06:05 UTC
``` sass
a {
  b: #ff6600;
}
```

Expected

``` sass
a{b:#f60}
```

Result

``` sass
a{b:#ff6600}
```

Removing the `;` fixes the issue.
Tested on Sass 3.4.20 and 4.0.0.alpha.1

**Comment by chriseppstein** [comment] 2016-01-04 21:23
Removing the `;` has no effect. But putting the color into a variable first does. I think this is a static parser issue. I think we shouldn't use any static parsing optimizations when outputting in compressed mode.

**Comment by chriseppstein** [comment] 2016-01-04 21:24
(This isn't the only such issue where static parsing messes up compression.)

**Comment by xzyfer** [comment] 2016-01-05 13:02
@chriseppstein when testing on Sass 3.4.20 and 4.0.0.alpha.1 removing the `;` did fix the issue.

My guess is that it's because the [STATIC_VALUE](https://github.com/sass/sass/blob/9077d95ffa6ab9388f59074483f1ef508d75d448/lib/sass/scss/rx.rb#L137) only matches if there is a trailing `[;}]`.

**Comment by mgreter** [comment] 2016-01-09 14:52
@chriseppstein any updates on the proposed fix presented by xzyfer?

**Comment by chriseppstein** [comment] 2016-04-28 18:35
@mgreter No work has been done on this yet, but I think it makes sense to not do any static parsing when in compressed mode so that we can always compress output the best.

**Comment by nex3** [comment] 2018-04-06 21:17
Duplicate of sass/ruby-sass#7

**Closed as completed by nex3** 2018-04-06 21:17 UTC
Labels: planned, help wanted
