### ISSUE TITLE
Feature Request: Ampersands after the beginning of a selector

### ISSUE THREAD

**Issue by jerek** [sass/sass#2855] opened 2020-05-04 16:45 UTC
## Summary

If Sass would support putting ampersands elsewhere in a selector than the beginning it would make it more flexible for complex situations. Currently this results in compile errors so supporting this wouldn't cause an issue with backwards compatibility, it would simply be a useful new feature.

### Current and Desired Results

When building selectors for classes that can be used on multiple types of elements there isn't currently a good way to add an element prefix to a set of selectors.

Example desired code:
```
.foo {
    &, &-left, &-right {
        div& {display:block}
        span& {display:inline}
    }
}
```

Example desired result:
```
div.foo, div.foo-left, div.foo-right {
  display: block;
}

span.foo, span.foo-left, span.foo-right {
  display: inline;
}
```

Example actual result:
```
Error: Invalid CSS after "div": expected "{", was "&"

       "&" may only be used at the beginning of a compound selector.
        on line [line number] of [scss file path]
>>         div& {display:block}
   -----------^
```

### Failed Workaround

A common suggestion for working around this is by using `@at-root element#{&}`, but this doesn't work for situations where `&` has multiple selectors.

Example failed workaround code:
```
.foo {
    &, &-left, &-right {
        @at-root div#{&} {display:block}
        @at-root span#{&} {display:inline}
    }
}
```

Example failed workaround result:
```
div.foo, .foo-left, .foo-right {
  display: block;
}

span.foo, .foo-left, .foo-right {
  display: inline;
}
```

**Comment by nex3** [comment] 2020-05-04 20:48
Duplicate of https://github.com/sass/sass/issues/1425

**Closed as completed by nex3** 2020-05-04 20:48 UTC
