### ISSUE TITLE
Umlauts in paths

### ISSUE THREAD

**Issue by ghost** [sass/sass#1632] opened 2015-02-10 09:09 UTC
Using SASS (3.2.19) with Netbeans (8.0.2) in Windows 7 does not resolve paths mit Umlauts when opening/writing to css files:

.../tüp/test.css will not be found
.../tup/test.css will be found

I think it is a SASS issue and not a Netbeans, ...

**Comment by nex3** [comment] 2015-02-13 21:20
Can you reproduce this just using the `sass` command-line interface? Also, what's your system encoding? What do you get when you run `ruby -e "puts Encoding.default_external"`? What about `ruby -e 'puts File.exist?("tüp/test.css")'` (run this one from the parent directory of `tüp/`)?

**Comment by chriseppstein** [comment] 2015-08-21 18:59
Closing due to unresponsiveness.

**Closed as completed by chriseppstein** 2015-08-21 18:59 UTC
