### ISSUE TITLE
Sass Mixin: Callback or Replace @content

### ISSUE THREAD

**Issue by caiotarifa** [sass/sass#2060] opened 2016-05-12 22:03 UTC
Hey,

I originally posted this question on StackOverflow, but as got no answer (even after a bounty), I am asking for your help through this channel.

http://stackoverflow.com/questions/37128950/sass-mixin-callback-or-replace-content

Is there any way to do this? Thank you.

**Comment by chriseppstein** [comment] 2016-05-13 17:53
Duplicate of #871

**Closed as completed by chriseppstein** 2016-05-13 17:53 UTC
