### ISSUE TITLE
& in placeholder not working

### ISSUE THREAD

**Issue by timkraut** [sass/sass#2445] opened 2018-01-11 16:49 UTC
Hi there,

I've just found an issue (not sure it it's a bug or a known limitation) with the `&` selector in a placeholder. The following code shows the issue:

```scss
%some-placeholder {
  color: blue; // Sass doesn't compile if no rules are defined here
  
  &--some-modifier {
    color: green;
  }
}

.some-class {
  @extend %some-placeholder;
}
```

See https://codepen.io/timkraut/pen/YYLZLV?editors=1100 for a live example.

The compiled CSS is:

```css
.some-class {
  color: blue;
}
```

I would have expected to see the following result:

```css
.some-class {
  color: blue;
}

.some-class--some-modifier {
  color: green;
}
```

**Comment by nex3** [comment] 2018-01-12 19:53
Duplicate of https://github.com/sass/sass/issues/2262. tl;dr: This is the expected behavior, because `&--some-modifier` is converted to `%some-placeholder--some-modifier` before `@extend` is ever run.

**Closed as completed by nex3** 2018-01-12 19:53 UTC
