### ISSUE TITLE
SASS converts color string to HEX value but only in 'compressed' output style.

### ISSUE THREAD

**Issue by dellow** [sass/sass#1981] opened 2016-01-29 16:12 UTC
I have a map of colors, if I try to loop through these and output the key for each colour some of them get converted to a HEX value but only when using the 'compressed' output style:

```
$colors: (
    black: (
        base: #000000
    ),
    white: (
        base: #FFFFFF
    ),
    blue: (
        base : #3498DB
    ),
    yellow: (
        base : #F1C40F
    )
);

@each $key, $value in $colors {
    @debug $key;
}
```

Outputs:

**Compressed:**

```
_buttons.scss:64 DEBUG: #000
_buttons.scss:64 DEBUG: #fff
_buttons.scss:64 DEBUG: blue
_buttons.scss:64 DEBUG: #ff0
```

**Expanded:**

```
_buttons.scss:64 DEBUG: black
_buttons.scss:64 DEBUG: white
_buttons.scss:64 DEBUG: blue
_buttons.scss:64 DEBUG: yellow
```

**Comment by cimmanon** [comment] 2016-01-29 17:59
Duplicate of https://github.com/sass/sass/issues/1256

**Comment by chriseppstein** [comment] 2016-01-29 19:39
Use quotes for color names that are actually strings and not references to a css color.

**Closed as completed by chriseppstein** 2016-01-29 19:39 UTC
