### ISSUE TITLE
min() and max() not parsed correctly when using plain CSS variables

### ISSUE THREAD

**Issue by mildred** [sass/sass#2935] opened 2020-11-03 17:55 UTC
When trying to use plain CSS min() and max() I get the following errors:

```
      width: min(100%, var(--c-make-forms--width))
            ^
          "var(--c-make-forms--width)" is not a number for `min'
```
```
  left: unquote(max(0, calc(calc(100% - var(--c-make-forms--width)) / 2)))
               ^
      "calc(calc(100% - var(--c-make-forms--width)) / 2)" is not a number for `max'
```

I believe this is because sass cannot parse CSS variables and get a number out of them. In this case, it should not be compiled in sass but should be outputted as plain CSS.

Workaround:

```sass
  width: unquote("min(100%, var(--c-make-forms--width))")
  left: unquote("max(0, calc(calc(100% - var(--c-make-forms--width)) / 2))")
```

Using sass 1.26.3

**Comment by Awjin** [comment] 2020-11-06 19:34
Plain CSS parsing for `width: min(100%, var(--c-make-forms--width))` is supported. I was unable to reproduce in both 1.26.3 and the latest version of Dart Sass.

**Comment by querkmachine** [comment] 2020-12-08 17:21
I believe this is already fixed in dart-sass. It's not a bug with Sass, per se, as the Sass implementation of `min` and `max` predates the CSS equivalents. 

An alternative method to the one above is to interpolate the function name with `#{}`, which always returns it as an unquoted string, e.g. `width: #{min}(100%, var(--c-make-forms--width))` would also work.

**Closed as completed** 2020-12-23 20:18 UTC
