### ISSUE TITLE
Don't output rules that just contain null and an !important declaration

### ISSUE THREAD

**Issue by danielguillan** [sass/sass#2089] opened 2016-06-28 12:16 UTC
Sass currently removes rules that contain no value, or better said, it removes those whose values are `null`.

This snippet...

``` scss
@function _() {
    @return null;
}

.foo {
   color: _();
}
```

... correctly outputs nothing.

When Sass encounters the delimiter token `!` and the keyword `important` following a `null` value it should remove the rule too.

This snippet...

``` scss
@function _() {
    @return null;
}

.foo {
   color: _() !important;
}
```

... should also output nothing too.

**Comment by chriseppstein** [comment] 2016-06-28 19:40
Duplicate of #1040

**Closed as completed by chriseppstein** 2016-06-28 19:40 UTC
