### ISSUE TITLE
Declare mixins and functions within mixin

### ISSUE THREAD

**Issue by ArmorDarks** [sass/sass#2470] opened 2018-02-06 19:11 UTC
Right now it is not possible to declare mixins or functions within another mixin.

So, this will throw an error:

```scss
@mixin someMixin () {
  @mixin internal () { ... }
  @function internal () { ... }
  ...
  @include internal(internal());
  '''
}
```

As replied in https://github.com/sass/sass/issues/2274#issuecomment-302548328, such restriction is logical.

However, because of that, we have to define internal methods of mixins outside of it. And it makes code much harder to read since internal mixin or function declaration will be encountered somewhere before or after the main mixin, and it's quite hard to immediately understand that's it's just an external method for specific mixin and shouldn't be used anywhere else:

```scss
@mixin internal () { ... }
@function internal () { ... }

@mixin someMixin () {
  ...
  @include internal(internal());
  '''
}
```

It also hard to tell here that `someMixin()` is actually has a dependency on those two completely detached "internal" methods.

More serious problem with it is that it will throw internal methods to the global context, which might be undesired and have side-effects. As of right now, such methods should be named in a specific way to ensure, that they can be identified by the developer as an external and to avoid collisions.

Something like:

```scss
@mixin _someMixin-internal () { ... }
@function _someMixin-internal () { ... }

@mixin someMixin () {
  ...
  @include _someMixin-internal(_someMixin-internal());
  '''
}
```

Which isn't practical and still doesn't guarante some ocassional collisions.

It would be great if after all in Sass it would be possible to define mixins and functions within other mixins.

**Comment by nex3** [comment] 2018-02-06 23:08
Duplicate of #127.

**Closed as completed by nex3** 2018-02-06 23:08 UTC

**Comment by ArmorDarks** [comment] 2018-02-07 09:35
Sorry for a duplicate. I've searched through the issues, but couldn't find it.

https://github.com/sass/sass/issues/127#issuecomment-220674930 still doesn't make it clear that some mixin or function belongs only to specific mixin and shouldn't be used. Even with modules system, it will be possible to import `internal` mixin and function (since they're in a global context of the imported file), which means that there is no way to provide a proper isolation.

**Comment by ArmorDarks** [comment] 2018-03-12 21:24
Sorry for being annoying, but ping @nex3

**Comment by nex3** [comment] 2018-03-13 00:17
The new module system will add the ability to declare mixins and functions that are private to a file and can't be used by files that import it. I think that will be sufficient to address this use-case.
