### ISSUE TITLE
Error reading src/styles/scss:src/styles/css: no such file or directory.

### ISSUE THREAD

**Issue by zcericola** [sass/sass#2504] opened 2018-04-15 00:34 UTC
Upgraded to dart sass and now I can't compile any of my sass projects. I keep getting the error above where it can't seem to find the files or directory even though the path is correct. I've tried using it with and without the --watch command. (I know now that the --watch command is not currently supported with dart sass). Any solutions?

**Comment by nex3** [comment] 2018-04-19 20:28
Duplicate of https://github.com/sass/dart-sass/issues/264

The colon-separated path syntax is a part of the `--watch`/`--update` interface. It's not implemented yet in Dart Sass, but it's high priority.

**Closed as completed by nex3** 2018-04-19 20:28 UTC
