### ISSUE TITLE
Error: RangeError: Invalid value: Not in inclusive range 0..29: -1

### ISSUE THREAD

**Issue by ghost** [sass/sass#3325] opened 2022-06-06 11:13 UTC
> Vue3.x + Element-plus + TypeScript

After upgrading `sass` to `1.52.2`, my project reported the following error:
```
6:55:21 [vite] Internal server error: RangeError: Invalid value: Not in inclusive range 0..29: -1
  Plugin: vite:css
  File: D:/xxxxxx/src/assets/styles/theme.scss
  Error: RangeError: Invalid value: Not in inclusive range 0..29: -1

```

But `sass@1.43.4` is OK.

**Comment by chryw** [comment] 2022-06-06 18:29
Also got this. v1.51.0 is ok.

**Comment by thinkh** [comment] 2022-06-07 14:16
For us version 1.52.1 worked and still does. Any idea what could cause this error in the last patch release?

**Comment by nex3** [comment] 2022-06-07 20:15
Duplicate of sass/dart-sass#1712.

**Closed as completed by nex3** 2022-06-07 20:15 UTC
