### ISSUE TITLE
how to use/define variable names with variable name 

### ISSUE THREAD

**Issue by anujaykumar1** [sass/sass#2017] opened 2016-03-17 15:03 UTC
like in less i can use @@var to [get value of a value](http://lesscss.org/features/#variables-feature-variable-names), how may i use this in sass ?

**Comment by cimmanon** [comment] 2016-03-17 15:05
Duplicate of https://github.com/sass/sass/issues/132

**Comment by chriseppstein** [comment] 2016-03-17 18:39
As noted in the issue linked by @cimmanon, the correct solution here is to use Sass maps which we added a couple versions ago to handle this use case.

**Closed as completed** 2016-03-17 18:39 UTC
