### ISSUE TITLE
Website no longer accessible 

### ISSUE THREAD

**Issue by roderickhsiao** [sass/sass#3329] opened 2022-06-10 22:48 UTC
it seems like the [documentation website](https://www.sass-lang.com/) no longer accessible?

**Comment by zaydek** [comment] 2022-06-11 01:04
You can use this as a fallback for now: https://web.archive.org/web/20220602164024/https://sass-lang.com.

**Comment by nex3** [comment] 2022-06-11 01:37
Duplicate of https://github.com/sass/sass-site/issues/641

**Closed as completed by nex3** 2022-06-11 01:37 UTC
