### ISSUE TITLE
Trailing Comma Support on Variables

### ISSUE THREAD

**Issue by heatherelliott** [sass/sass#1720] opened 2015-05-07 17:29 UTC
Please make this a thing:
$font-link-hover, $border-dark: #cccccc;

That way I could keep all the colors on my style sheet as what they are so if I have to change it later I'll know what I'm changing. Instead of dark-grey which is where am I using this color?

And if they needed to be split up later it would make it so much easier to change. And know what I'm changing. Please?

**Comment by nex3** [comment] 2015-05-08 21:00
Duplicate of #109. This isn't exactly the same issue, but we'll probably do it for variables if and only if we do it for properties.

**Closed as completed by nex3** 2015-05-08 21:00 UTC
