### ISSUE TITLE
Treat CSS color functions with CSS variables inside as literals

### ISSUE THREAD

**Issue by AmeliaBR** [sass/sass#2175] opened 2016-10-19 17:42 UTC
See this demo & tweet thread from Ana Tudor: https://twitter.com/anatudor/status/788787341854969856

The issue: Sass tries to parse `hsl()` and other color functions, instead of passing them to the browser.  A CSS variable call (`var(--value)`) inside that color function therefore causes a parse error in Sass/SCSS, despite being perfectly valid CSS.

There are work-arounds, using either string interpolation, or by using a `calc` function to wrap the variable call:

``` scss
    /* parse error *
    background: linear-gradient(
        hsl(var(--hue), 100%, 75%), 
        hsl(var(--hue), 100%, 25%));
    /**/
    /* works (string interpolation) */
    background: #{'linear-gradient(
        hsl(var(--hue), 100%, 75%), 
        hsl(var(--hue), 100%, 25%))'};
    /**/
    /* works (calc function wrapper) */
    background: linear-gradient(
        hsl(calc(var(--hue)), 100%, 75%), 
        hsl(calc(var(--hue)), 100%, 25%));
    /**/
```

But if `calc()` is recognized by Sass & causes the `hsl` function to be passed to the browser, it shouldn't be too hard to make `var()` do the same.

**Comment by stevenvachon** [comment] 2016-10-27 17:10
Duplicate of #2078

**Comment by nex3** [comment] 2016-12-11 23:49
@stevenvachon I don't think this is a duplicate of that. This is specifically about passing `var()` to the existing plain-CSS functions.

**Comment by stevenvachon** [comment] 2016-12-12 18:50
Sass doesn't support plain CSS color functions. How can it then be expected to support `var()` in them?

**Comment by AmeliaBR** [comment] 2016-12-12 19:52
> Sass doesn't support plain CSS color functions. How can it then be expected to support var() in them?

How do you support `calc()` inside a color function? The request is to treat `var()` the exact same way you treat `calc()`: by passing the values through to the compiled CSS, un-modified.

**Closed as completed** 2017-01-14 19:27 UTC
Labels: CSS compatibility
