### ISSUE TITLE
Commenting out undefined SCSS variables

### ISSUE THREAD

**Issue by CodyCahoon** [sass/sass#1971] opened 2016-01-18 06:31 UTC
When you comment out an undefined variable using /\* */ in your SCSS file, sass does not compile.

``` css

/*
    .test-class{
        background:#{$undefinedVariable};
    }
*/

```

``` unix
$user: sass test.scss 
Error: Undefined variable: "$undefinedVariable".
        on line 3 of test.scss
  Use --trace for backtrace.
```

**Comment by davidkpiano** [comment] 2016-01-18 12:16
That's because in CSS comments, which are `/* these comments */` and not `// these comments`, variables can be interpolated:

``` scss
$component: button;

/* The #{$component} component */
.button {
  display: block;
}
```

**Output:**

``` css
/* The button component */
.button {
  display: block;
}
```

**Comment by cimmanon** [comment] 2016-01-18 13:06
Duplicate of https://github.com/sass/sass/issues/1123

**Comment by chriseppstein** [comment] 2016-01-18 17:55
This is not a bug. Interpolation is a feature of CSS comments. Use Sass comments (`//`) to comment out sass code.

**Closed as completed by chriseppstein** 2016-01-18 17:55 UTC
