### ISSUE TITLE
SASS should remove unneccesary * selectors

### ISSUE THREAD

**Issue by CupOfTea696** [sass/sass#2380] opened 2017-09-28 13:42 UTC
I'm just gonna illustrate this with an example because I think that'd make more sense.

**SCSS:**
```scss
#container > * {
  margin: 32px 0;
  
  &:first-child {
    margin-top: 0;
  }
  
  &:last-child {
    margin-bottom: 0;
  }
}
```

**Expected/Desired Result:**
```css
#container > * {
  margin: 32px 0;
}
#container > :first-child {
  margin-top: 0;
}
#container > :last-child {
  margin-bottom: 0;
}
```

**Actual Result:**
```css
#container > * {
  margin: 32px 0;
}
#container > *:first-child {
  margin-top: 0;
}
#container > *:last-child {
  margin-bottom: 0;
}
```

**Comment by nex3** [comment] 2017-09-29 23:16
This would be nice to have. One thing I've thought about for a while but never investigated the feasibility of is re-using `@extend`'s compound selector unification logic to combine the parent and child selector. That would automatically eliminate universal selectors, as well as likely providing more semantics results in other situations.

**Comment by nex3** [comment] 2018-04-11 22:32
Duplicate of #490

**Closed as completed by nex3** 2018-04-11 22:32 UTC
Labels: enhancement
