### ISSUE TITLE
How to embed a CSS file into current output?

### ISSUE THREAD

**Issue by abibell** [sass/sass#1893] opened 2015-11-12 20:01 UTC
# Application Scenario

External Vendor css files that are loaded using ``@import` is too slow compared to embedding (copy/paste). I realise it is a planned feature.
# Application Solution

Embed those specific notorious css files in the master.sass file
# Noted concerns and alternates
- Admins didn't want to use `!force` in the past
- Admins wanted to use @use syntax, which I am not sure what it is or where it is
- I like @chriseppstein extension and liked it for a while now. Just looking at web as such there are already technologies (UI applications) for technologies (Web) for technologies (CSS) for technologies (SASS). I pity the younger kids who have to learn all this and find a full-stack job knowing all the 100 languages and frameworks.
# Request
- What syntax can we use? `@include "folder/file.css"`? Since include seems to be popular term in several languages/frameworks ng-include, #include and so on.
- What is a simple clean built-in solution in SASS?

**Comment by chriseppstein** [comment] 2015-11-12 22:59
Duplicate of #556

**Closed as completed by chriseppstein** 2015-11-12 22:59 UTC

**Comment by abibell** [comment] 2015-11-13 08:18
It is. Conversation is locked. There is no way to ask a question on that.

What is the solution approach for that? I am just after solution blessings, so I can implement it on the weekend. If someone is already on it, what is the rough ETA?
